### import packages

In [1]:
import openai
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### create qdrant collection for hybrid search
previous qdrant db use cosine similarity to create a collection, since we are going to run hydrib search, so we need to create a new qdrant collection

In [2]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [3]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-hybrid-search",
    # name the vector field as "text-embedding-3-small", before we did not name it as we only have one vector field
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(modifier=Modifier.IDF)
    }
)

True

In [4]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-01-hybrid-search",
    field_name = 'parent_asin',
    field_schema = PayloadSchemaType.KEYWORD # run keyword search against parent_asin
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### embedding function

In [36]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [37]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Read the sampled dataset with Amazon inventory data

In [7]:
df_items = pd.read_json("../../data/raw/meta_Electronics_2022_2023_ratings_100_sample_1000.jsonl", lines=True)

In [8]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Computers,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,4.5,153,[Specifically Designed For: Samsung Galaxy Tab...,[Specifically design for Samsung Galaxy Tab E ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Leafbook,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7 Inches', '...",B01DJI7TP8,NaN,NaN,NaN
1,All Electronics,Lume Cube AIR Video Conference Lighting Kit - ...,3.7,215,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],LUME CUBE,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '1.61 x 1.61 x 1.1 inch...,B07M6SWKLT,NaN,NaN,NaN
2,All Electronics,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,4.5,1278,[Insanely good 360˚ sound - Ultimate Ears Boom...,[Ultimate Ears boom 2 is the 360-degree wirele...,68.49,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'HONEST review of the UE Boom 2 spe...,Ultimate Ears,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '2.75 x 2.75 x 7.08 inc...,B07J31M7PW,NaN,NaN,NaN
3,All Electronics,Seagate FreeAgent GoFlex TV STAJ100,3.5,108,[Watch streaming media directly from the Inter...,"[Product Description, The Seagate GoFlex TV HD...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Seagate,"[Electronics, Television & Video, Streaming Me...","{'Brand Name': 'Seagate', 'Item Weight': '10.7...",B003IT6YFK,NaN,NaN,NaN
4,All Electronics,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",4.5,110,[🎧【High-quality Stereo Sound】Built-in multiple...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'J&D 2RCA Male to 2RCA Male Cable',...",JSAUX,"[Electronics, Television & Video, Accessories,...",{'Package Dimensions': '10.16 x 3.15 x 0.71 in...,B099ZPY68J,NaN,NaN,NaN

### Preprocess title and features

In [9]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

def extract_first_large_image(row):
    return row["images"][0].get("large", "")

df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,Computers,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,4.5,153,[Specifically Designed For: Samsung Galaxy Tab...,[Specifically design for Samsung Galaxy Tab E ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Leafbook,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7 Inches', '...",B01DJI7TP8,NaN,NaN,NaN,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,https://m.media-amazon.com/images/I/51PML408lo...
1,All Electronics,Lume Cube AIR Video Conference Lighting Kit - ...,3.7,215,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],LUME CUBE,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '1.61 x 1.61 x 1.1 inch...,B07M6SWKLT,NaN,NaN,NaN,Lume Cube AIR Video Conference Lighting Kit - ...,https://m.media-amazon.com/images/I/411wKstRw1...
2,All Electronics,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,4.5,1278,[Insanely good 360˚ sound - Ultimate Ears Boom...,[Ultimate Ears boom 2 is the 360-degree wirele...,68.49,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'HONEST review of the UE Boom 2 spe...,Ultimate Ears,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '2.75 x 2.75 x 7.08 inc...,B07J31M7PW,NaN,NaN,NaN,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,https://m.media-amazon.com/images/I/41kYEBxNW2...
3,All Electronics,Seagate FreeAgent GoFlex TV STAJ100,3.5,108,[Watch streaming media directly from the Inter...,"[Product Description, The Seagate GoFlex TV HD...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Seagate,"[Electronics, Television & Video, Streaming Me...","{'Brand Name': 'Seagate', 'Item Weight': '10.7...",B003IT6YFK,NaN,NaN,NaN,Seagate FreeAgent GoFlex TV STAJ100 Watch stre...,https://m.media-amazon.com/images/I/31Vy2ogKvD...
4,All Electronics,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",4.5,110,[🎧【High-quality Stereo Sound】Built-in multiple...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'J&D 2RCA Male to 2RCA Male Cable',...",JSAUX,"[Electronics, Television & Video, Accessories,...",{'Package Dimensions': '10.16 x 3.15 x 0.71 in...,B099ZPY68J,NaN,NaN,NaN,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",https://m.media-amazon.com/images/I/41EbtDHhNE...

In [12]:
df_items.shape

(1000, 18)

In [10]:
list(df_items["preprocessed_description"].items())[0]

(0,
 "Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lightweight Shell Case for Samsung Galaxy Tab E lite 7.0 & Tab 3 Lite T110/T111, Black Specifically Designed For: Samsung Galaxy Tab 3 Lite 7.0 7'' T110 T111 Tablet / Galaxy Tab E Lite 7.0 (NOT FIT FOR Samsung Galaxy Tab 3 7.0 T210) Premium PU leather exterior and microfiber interior. Ultra slim and lightweight hard back design adds minimal bulk while protecting your precious device. Precise cut-outs and openings for easy access to all tablet features. Cover has flip capability to transform the case into a viewing stand and keyboard stand. One piece case, the front and back does not separate. Various colors are available.Magnetic closure.")

In [11]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/51PML408loL._AC_.jpg')

In [14]:
df_data_to_embed = df_items[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]
data_to_embed = df_data_to_embed.to_dict(orient="records")

In [16]:
len(data_to_embed)

1000

In [15]:
text_to_embed = [item["preprocessed_description"] for item in data_to_embed]

In [19]:
embeddings = get_embeddings_batch(text_to_embed)

Processed 100 of 1000
Processed 200 of 1000
Processed 300 of 1000
Processed 400 of 1000
Processed 500 of 1000
Processed 600 of 1000
Processed 700 of 1000
Processed 800 of 1000
Processed 900 of 1000
Processed 1000 of 1000

In [20]:
len(embeddings)

1000

In [28]:
pointstructs = []
i= 1
for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(PointStruct(
        id=i,
        vector={"text-embedding-3-small": embedding, 
        "bm25": 
            Document(text=data["preprocessed_description"], model="qdrant/bm25")}, # qdrant handle it natively
        payload=data
    ))
    i+=1

In [29]:
pointstructs[0].vector

{'text-embedding-3-small': [0.027679443359375,
  -0.06182861328125,
  -0.01552581787109375,
  0.0121307373046875,
  -0.0174407958984375,
  -0.0278778076171875,
  0.0120391845703125,
  0.040130615234375,
  0.0382080078125,
  -0.022430419921875,
  -0.0302886962890625,
  -0.01849365234375,
  -0.0174713134765625,
  0.0258026123046875,
  0.00899505615234375,
  0.03125,
  0.0712890625,
  -0.020538330078125,
  -0.024505615234375,
  0.0631103515625,
  -0.003330230712890625,
  0.01030731201171875,
  0.03973388671875,
  0.00672149658203125,
  -0.01453399658203125,
  -0.04595947265625,
  0.00635528564453125,
  -0.0369873046875,
  0.0023345947265625,
  0.01108551025390625,
  0.04071044921875,
  -0.0169830322265625,
  0.032440185546875,
  -0.0782470703125,
  -0.049835205078125,
  -0.0017843246459960938,
  0.036224365234375,
  -0.038726806640625,
  -0.01500701904296875,
  0.045989990234375,
  -0.0005006790161132812,
  0.0462646484375,
  0.035614013671875,
  0.0180816650390625,
  0.007656097412109375,
  -0.0126800537109375,
  0.01561737060546875,
  0.06085205078125,
  -0.0209197998046875,
  -0.0054168701171875,
  0.012939453125,
  -0.00908660888671875,
  0.00563812255859375,
  0.05908203125,
  -0.03607177734375,
  -0.00543975830078125,
  -0.035919189453125,
  0.013824462890625,
  0.03094482421875,
  0.0012798309326171875,
  -0.06256103515625,
  -0.0020122528076171875,
  -0.02593994140625,
  0.06536865234375,
  -0.0390625,
  -0.025543212890625,
  -0.050506591796875,
  -0.035400390625,
  -0.050323486328125,
  -0.058441162109375,
  0.01425933837890625,
  -0.057891845703125,
  -0.04364013671875,
  -0.034210205078125,
  -0.0018520355224609375,
  0.043701171875,
  0.0236358642578125,
  -0.03021240234375,
  -0.0030803680419921875,
  0.02301025390625,
  0.0162353515625,
  0.0054473876953125,
  -0.0005483627319335938,
  0.036376953125,
  -0.05792236328125,
  0.0151824951171875,
  -0.059906005859375,
  -0.010955810546875,
  -0.0594482421875,
  0.00397491455078125,
  0.0235748291015625,
  -0.0474853515625,
  -0.02496337890625,
  -0.01861572265625,
  0.02044677734375,
  0.019195556640625,
  -0.05255126953125,
  0.00138092041015625,
  0.002902984619140625,
  0.040771484375,
  0.0396728515625,
  -0.0059051513671875,
  -0.0218505859375,
  -0.05712890625,
  0.03900146484375,
  0.044036865234375,
  -0.01971435546875,
  -0.029693603515625,
  -0.0170135498046875,
  -0.016082763671875,
  -0.024017333984375,
  -0.0235595703125,
  0.02056884765625,
  0.022857666015625,
  0.022796630859375,
  0.01465606689453125,
  0.09088134765625,
  0.0035610198974609375,
  -0.0204925537109375,
  -0.0433349609375,
  0.00563812255859375,
  0.04254150390625,
  0.0396728515625,
  -0.058563232421875,
  -0.01593017578125,
  -0.0135498046875,
  -0.0279998779296875,
  -0.039031982421875,
  -0.053558349609375,
  0.052337646484375,
  0.0198974609375,
  -0.001865386962890625,
  0.035614013671875,
  -0.0295257568359375,
  0.01214599609375,
  -0.0156707763671875,
  0.0267486572265625,
  -0.0169830322265625,
  -8.624792098999023e-05,
  -0.026763916015625,
  -0.0114593505859375,
  0.004222869873046875,
  0.034515380859375,
  0.0261077880859375,
  -0.0333251953125,
  0.0281982421875,
  0.026885986328125,
  0.01934814453125,
  -0.00014150142669677734,
  0.03839111328125,
  0.007350921630859375,
  0.0022220611572265625,
  0.01041412353515625,
  -0.01190948486328125,
  0.002468109130859375,
  -0.04351806640625,
  0.021942138671875,
  0.034637451171875,
  -0.02972412109375,
  0.0246429443359375,
  0.0040740966796875,
  -0.032745361328125,
  0.00222015380859375,
  -0.00981903076171875,
  -0.045806884765625,
  0.04779052734375,
  -8.934736251831055e-05,
  -0.041656494140625,
  -0.06439208984375,
  0.03729248046875,
  0.01450347900390625,
  0.030303955078125,
  -0.04534912109375,
  0.0144500732421875,
  -0.0083160400390625,
  -0.046234130859375,
  0.02960205078125,
  0.011199951171875,
  0.0184326171875,
  0.0190277099609375,
  -0.0201568603515625,
  -0.0013933181762695312,
  -0.0244598388671875,
  -0.021636962890625,
  0.00939178466796875,
  0.0214385986328125,
  0.0242919921875,
  -0.030975341796875,
  -0.05535888671875,
  -0.0711669921875,
  -0.004390716552734375,
  0.0247650146484375,
  -0.00592041015625,
  -0.03460693359375,
  -0.033935546875,
  0.002552032470703125,
  -0.0016012191772460938,
  -0.0183258056640625,
  -0.022430419921875,
  0.027801513671875,
  -0.0286712646484375,
  0.0305023193359375,
  -0.032562255859375,
  0.0288238525390625,
  0.0267181396484375,
  0.0214385986328125,
  -0.04205322265625,
  0.04644775390625,
  0.04083251953125,
  -0.0248870849609375,
  0.032562255859375,
  0.05865478515625,
  -0.036285400390625,
  -0.0435791015625,
  0.01715087890625,
  0.0307159423828125,
  0.016845703125,
  -0.06707763671875,
  -0.01318359375,
  0.041107177734375,
  -0.026336669921875,
  -0.01708984375,
  0.0540771484375,
  -0.0222625732421875,
  -0.0202484130859375,
  -0.0148773193359375,
  -0.00099945068359375,
  -0.039398193359375,
  0.00026679039001464844,
  -0.013427734375,
  -0.0007982254028320312,
  0.0377197265625,
  -0.002777099609375,
  0.0227508544921875,
  0.039825439453125,
  -0.032928466796875,
  -0.06085205078125,
  -0.01331329345703125,
  -0.01076507568359375,
  -0.030792236328125,
  -0.0277252197265625,
  0.031463623046875,
  -0.0567626953125,
  0.016021728515625,
  0.024139404296875,
  -0.0208740234375,
  -0.0019178390502929688,
  -0.049652099609375,
  0.0210113525390625,
  0.01277923583984375,
  0.035186767578125,
  0.032989501953125,
  0.043182373046875,
  -0.001949310302734375,
  0.035675048828125,
  -0.0006198883056640625,
  0.006290435791015625,
  0.02020263671875,
  0.0026645660400390625,
  -0.0298919677734375,
  -0.01136016845703125,
  -0.0203857421875,
  0.021392822265625,
  -0.0147247314453125,
  0.034454345703125,
  0.014434814453125,
  0.0265960693359375,
  -0.01085662841796875,
  -0.00926971435546875,
  0.003932952880859375,
  0.05340576171875,
  -0.018341064453125,
  -0.05633544921875,
  0.01299285888671875,
  -0.007511138916015625,
  -0.0308685302734375,
  -0.051513671875,
  -0.03265380859375,
  0.01465606689453125,
  0.01491546630859375,
  0.0099334716796875,
  -0.021331787109375,
  -0.0660400390625,
  -0.022216796875,
  -0.01139068603515625,
  0.049163818359375,
  0.01763916015625,
  -0.01499176025390625,
  -0.0285186767578125,
  -0.041229248046875,
  0.055694580078125,
  -0.07855224609375,
  -0.00792694091796875,
  -0.037994384765625,
  -0.057891845703125,
  -0.0217742919921875,
  0.0079803466796875,
  0.048583984375,
  -0.02630615234375,
  0.0255279541015625,
  0.006114959716796875,
  -0.0065155029296875,
  -0.005645751953125,
  -0.025238037109375,
  0.0189971923828125,
  -0.01300048828125,
  -0.0024261474609375,
  -0.054412841796875,
  -0.036102294921875,
  -0.0254669189453125,
  -0.01293182373046875,
  0.0172271728515625,
  -0.0099029541015625,
  -0.054840087890625,
  -0.016357421875,
  -0.04754638671875,
  -0.064697265625,
  0.03997802734375,
  -0.0330810546875,
  -0.03314208984375,
  0.07476806640625,
  -0.0208740234375,
  -0.0307464599609375,
  0.0166015625,
  -0.006195068359375,
  0.0202789306640625,
  0.00397491455078125,
  0.0115814208984375,
  -0.0207061767578125,
  -0.00460052490234375,
  0.0014333724975585938,
  -0.049041748046875,
  0.0167694091796875,
  -0.05413818359375,
  -0.0124664306640625,
  0.0029449462890625,
  0.0114288330078125,
  -0.015655517578125,
  -0.06671142578125,
  0.0246124267578125,
  -0.021148681640625,
  -0.0498046875,
  -0.034820556640625,
  -0.01123809814453125,
  -0.0005946159362792969,
  -0.03948974609375,
  0.02984619140625,
  -0.00833892822265625,
  0.0555419921875,
  0.021270751953125,
  -0.031494140625,
  0.01375579833984375,
  0.0400390625,
  -0.05633544921875,
  -0.0098724365234375,
  -0.05133056640625,
  -0.00023114681243896484,
  -0.075439453125,
  0.007518768310546875,
  0.0230560302734375,
  0.04046630859375,
  -0.0127105712890625,
  -0.006374359130859375,
  -0.0026874542236328125,
  0.00791168212890625,
  0.02227783203125,
  -0.045318603515625,
  0.01010894775390625,
  0.025543212890625,
  -0.0196990966796875,
  0.05316162109375,
  -0.027069091796875,
  -0.0203094482421875,
  0.00042319297790527344,
  -0.054595947265625,
  -0.048553466796875,
  -0.006725311279296875,
  0.0287322998046875,
  -0.032562255859375,
  -0.0426025390625,
  -0.013916015625,
  0.0232696533203125,
  0.01184844970703125,
  -0.00124359130859375,
  0.03564453125,
  -0.006195068359375,
  -0.0307464599609375,
  -0.004985809326171875,
  0.0621337890625,
  0.04217529296875,
  0.0126190185546875,
  0.02880859375,
  0.0295257568359375,
  -0.026458740234375,
  0.0469970703125,
  0.045623779296875,
  -0.0027065277099609375,
  0.04278564453125,
  0.014190673828125,
  -0.056976318359375,
  0.021636962890625,
  0.006977081298828125,
  0.03009033203125,
  -0.00545501708984375,
  -0.018218994140625,
  -0.089599609375,
  0.000823974609375,
  -0.0026721954345703125,
  0.0203094482421875,
  -0.033782958984375,
  0.00876617431640625,
  -0.027130126953125,
  -0.01074981689453125,
  0.031341552734375,
  0.0008459091186523438,
  -0.0021533966064453125,
  -0.0044708251953125,
  0.0200347900390625,
  0.003841400146484375,
  -0.00823974609375,
  0.0188446044921875,
  -0.0254974365234375,
  0.006809234619140625,
  0.06365966796875,
  -0.0246734619140625,
  -0.000583648681640625,
  0.008697509765625,
  0.0091094970703125,
  -0.0014810562133789062,
  -0.007221221923828125,
  0.003063201904296875,
  0.0204925537109375,
  0.01274871826171875,
  -0.01168060302734375,
  -0.00860595703125,
  -0.04351806640625,
  -0.031829833984375,
  0.01013946533203125,
  -0.036865234375,
  -0.03216552734375,
  -0.042694091796875,
  -0.0191192626953125,
  -0.00279998779296875,
  0.02825927734375,
  0.071533203125,
  -0.014862060546875,
  -0.003955841064453125,
  0.051788330078125,
  -0.0224151611328125,
  -0.0156707763671875,
  -0.037109375,
  0.0093231201171875,
  0.005062103271484375,
  0.0537109375,
  -0.0178070068359375,
  -0.03985595703125,
  -0.0166168212890625,
  -0.02777099609375,
  0.043914794921875,
  -0.0132598876953125,
  0.0145721435546875,
  0.016632080078125,
  0.044219970703125,
  -0.00891876220703125,
  -0.0294647216796875,
  -0.01203155517578125,
  0.007171630859375,
  0.03729248046875,
  0.032684326171875,
  -0.01092529296875,
  0.007328033447265625,
  0.0147247314453125,
  0.0008759498596191406,
  0.01038360595703125,
  0.0245361328125,
  0.06549072265625,
  -0.01371002197265625,
  -0.02435302734375,
  0.034332275390625,
  -0.001556396484375,
  -0.029205322265625,
  -0.0020160675048828125,
  -0.0692138671875,
  -0.01129150390625,
  -0.0170745849609375,
  0.0293731689453125,
  0.0286102294921875,
  0.01116943359375,
  -0.0218505859375,
  -0.01120758056640625,
  -0.02606201171875,
  -0.02239990234375,
  0.01934814453125,
  -0.004528045654296875,
  0.046539306640625,
  0.025421142578125,
  -0.03411865234375,
  -0.059661865234375,
  0.0220489501953125,
  0.030914306640625,
  0.0023899078369140625,
  -0.0309295654296875,
  0.005859375,
  0.0178680419921875,
  -0.0148773193359375,
  0.03662109375,
  -0.004024505615234375,
  -0.003376007080078125,
  -0.0114593505859375,
  0.0193634033203125,
  -0.022552490234375,
  -0.01922607421875,
  0.002475738525390625,
  -0.0239715576171875,
  0.00839996337890625,
  -0.0302734375,
  -0.0352783203125,
  0.049530029296875,
  0.0089263916015625,
  -0.07281494140625,
  -0.023162841796875,
  -0.007671356201171875,
  0.0246734619140625,
  -0.025299072265625,
  0.028167724609375,
  -0.0185089111328125,
  -0.005908966064453125,
  -0.05377197265625,
  -0.0660400390625,
  -0.0693359375,
  0.0052337646484375,
  -0.036651611328125,
  -0.05029296875,
  0.0030651092529296875,
  -0.0125885009765625,
  0.0157928466796875,
  0.00910186767578125,
  0.01043701171875,
  -0.02056884765625,
  -0.006855010986328125,
  0.0139312744140625,
  0.0017843246459960938,
  0.021636962890625,
  0.017852783203125,
  0.031890869140625,
  -0.03302001953125,
  0.0181121826171875,
  0.01079559326171875,
  0.011474609375,
  -0.0016012191772460938,
  0.0489501953125,
  -0.0031871795654296875,
  0.03704833984375,
  -0.045562744140625,
  -0.00632476806640625,
  0.01593017578125,
  -0.028900146484375,
  0.0032329559326171875,
  -0.0019445419311523438,
  0.0253753662109375,
  -0.0308074951171875,
  0.0166168212890625,
  -0.0070648193359375,
  -0.02716064453125,
  -0.0028839111328125,
  0.019439697265625,
  -0.00948333740234375,
  -0.0164794921875,
  -0.06988525390625,
  0.021514892578125,
  -0.0279998779296875,
  -0.0010471343994140625,
  0.015655517578125,
  -0.01363372802734375,
  0.039581298828125,
  0.004688262939453125,
  -0.00742340087890625,
  -0.01139068603515625,
  -0.0287933349609375,
  -0.005649566650390625,
  -0.02093505859375,
  -0.0240020751953125,
  -0.0394287109375,
  0.038299560546875,
  -0.0198974609375,
  0.0091705322265625,
  0.015838623046875,
  -0.043182373046875,
  -0.014739990234375,
  0.042816162109375,
  0.0008444786071777344,
  -0.035003662109375,
  -0.021026611328125,
  0.019287109375,
  0.0206298828125,
  -0.0091094970703125,
  -0.05810546875,
  0.00505828857421875,
  -0.00041031837463378906,
  -0.004375457763671875,
  -0.01003265380859375,
  -0.00347137451171875,
  0.003448486328125,
  0.0306243896484375,
  -0.00879669189453125,
  0.0026988983154296875,
  0.03704833984375,
  0.0032367706298828125,
  -0.033294677734375,
  0.022552490234375,
  0.0262451171875,
  -0.0131988525390625,
  -0.03948974609375,
  0.0102386474609375,
  -0.006496429443359375,
  -0.00818634033203125,
  0.0154876708984375,
  -0.01502227783203125,
  0.0300445556640625,
  -0.005382537841796875,
  0.0092620849609375,
  0.0087890625,
  0.03411865234375,
  -0.0011320114135742188,
  0.00016498565673828125,
  0.00601959228515625,
  -0.03533935546875,
  0.0132904052734375,
  0.0122222900390625,
  -0.034027099609375,
  -0.002532958984375,
  -0.0183258056640625,
  0.01806640625,
  0.0216217041015625,
  -0.00948333740234375,
  -0.0036106109619140625,
  -0.002574920654296875,
  0.0298309326171875,
  -0.0069580078125,
  0.0031642913818359375,
  -0.01666259765625,
  -0.005153656005859375,
  0.01409912109375,
  -0.0208282470703125,
  -0.00753021240234375,
  0.0207977294921875,
  -0.002460479736328125,
  0.01485443115234375,
  -0.0171356201171875,
  -0.007617950439453125,
  0.05523681640625,
  0.0033245086669921875,
  0.038299560546875,
  0.00514984130859375,
  0.0121917724609375,
  0.003032684326171875,
  0.0040283203125,
  0.003711700439453125,
  -0.0280914306640625,
  0.00405120849609375,
  -0.0121917724609375,
  0.0186920166015625,
  -0.01099395751953125,
  -0.01467132568359375,
  -0.01678466796875,
  -0.026641845703125,
  -0.00215911865234375,
  -0.027923583984375,
  -0.035369873046875,
  -0.01079559326171875,
  0.0293426513671875,
  -0.00293731689453125,
  -0.001068115234375,
  -0.0031719207763671875,
  0.0311431884765625,
  -0.00434112548828125,
  0.0002906322479248047,
  0.004238128662109375,
  -0.0062408447265625,
  -0.02764892578125,
  -0.012603759765625,
  0.01357269287109375,
  -0.015899658203125,
  0.0106658935546875,
  -0.0017490386962890625,
  0.002777099609375,
  -0.036590576171875,
  0.019073486328125,
  0.016632080078125,
  0.00360107421875,
  0.01309967041015625,
  0.0127105712890625,
  0.0606689453125,
  -0.010467529296875,
  -0.03125,
  0.036346435546875,
  0.01316070556640625,
  0.0014801025390625,
  -0.0010080337524414062,
  -0.040252685546875,
  -0.0190582275390625,
  0.045379638671875,
  -0.007671356201171875,
  -0.0262451171875,
  -0.009674072265625,
  -0.001544952392578125,
  -0.0245361328125,
  0.00041103363037109375,
  0.005657196044921875,
  -0.034271240234375,
  -0.0031833648681640625,
  0.01268768310546875,
  -0.005390167236328125,
  -0.044036865234375,
  -0.0211944580078125,
  0.006153106689453125,
  -0.0095062255859375,
  0.0240936279296875,
  0.0285186767578125,
  -0.0009088516235351562,
  0.002716064453125,
  0.04547119140625,
  -0.0259246826171875,
  -0.04022216796875,
  0.00955963134765625,
  -0.005584716796875,
  0.0221099853515625,
  0.0124969482421875,
  0.0009469985961914062,
  -0.035614013671875,
  0.0093536376953125,
  0.023834228515625,
  -0.00038743019104003906,
  0.01171112060546875,
  -0.0190277099609375,
  0.021636962890625,
  -0.006900787353515625,
  -0.03076171875,
  -0.03387451171875,
  -0.005870819091796875,
  -0.003223419189453125,
  0.016510009765625,
  0.00319671630859375,
  -0.003932952880859375,
  0.00225067138671875,
  0.019195556640625,
  -0.01019287109375,
  0.0242156982421875,
  0.012908935546875,
  0.005023956298828125,
  0.035552978515625,
  0.003063201904296875,
  0.0133209228515625,
  0.005970001220703125,
  0.0018529891967773438,
  0.0167999267578125,
  -0.0018768310546875,
  0.00208282470703125,
  0.0182037353515625,
  0.0243377685546875,
  0.016082763671875,
  0.029266357421875,
  -0.01013946533203125,
  0.056182861328125,
  -0.020416259765625,
  -0.035430908203125,
  -0.062469482421875,
  -0.0131072998046875,
  -0.0335693359375,
  0.033660888671875,
  -0.018951416015625,
  -0.0113983154296875,
  -0.004261016845703125,
  0.0252838134765625,
  0.0209503173828125,
  -0.0041046142578125,
  -0.002696990966796875,
  0.02447509765625,
  0.0150146484375,
  -0.002696990966796875,
  -0.015106201171875,
  -0.01434326171875,
  0.001781463623046875,
  0.0284271240234375,
  -0.0066070556640625,
  0.0206146240234375,
  0.016632080078125,
  0.0261993408203125,
  -0.026702880859375,
  0.01392364501953125,
  0.00445556640625,
  -0.01806640625,
  -0.0172119140625,
  -0.014251708984375,
  -0.004421234130859375,
  0.00577545166015625,
  -0.00724029541015625,
  -0.01502227783203125,
  0.00823974609375,
  0.007061004638671875,
  -0.00812530517578125,
  0.0181121826171875,
  -0.0176849365234375,
  -0.037811279296875,
  0.002452850341796875,
  0.025787353515625,
  -0.03173828125,
  0.00342559814453125,
  -0.0031070709228515625,
  -0.035247802734375,
  0.00772857666015625,
  0.0196685791015625,
  -0.02325439453125,
  0.03277587890625,
  0.00325775146484375,
  0.015716552734375,
  -0.0028324127197265625,
  -0.016326904296875,
  0.0027751922607421875,
  0.0257415771484375,
  0.010833740234375,
  -0.0472412109375,
  0.0099334716796875,
  0.012176513671875,
  -0.0024623870849609375,
  -0.0243988037109375,
  -0.006855010986328125,
  0.0145416259765625,
  -0.035491943359375,
  -0.0133819580078125,
  -0.0021114349365234375,
  -0.01535797119140625,
  0.0255584716796875,
  0.003643035888671875,
  0.01294708251953125,
  0.006610870361328125,
  -0.03680419921875,
  0.0098419189453125,
  -0.010040283203125,
  0.01229095458984375,
  0.040557861328125,
  -0.0001518726348876953,
  -0.035430908203125,
  -0.046356201171875,
  -0.00201416015625,
  0.0009350776672363281,
  -0.00775146484375,
  0.0219573974609375,
  0.01605224609375,
  0.029144287109375,
  0.014312744140625,
  -0.00511932373046875,
  -0.0309295654296875,
  0.005840301513671875,
  0.01444244384765625,
  -0.0118865966796875,
  0.010986328125,
  -0.050567626953125,
  -0.0186767578125,
  -0.02301025390625,
  -0.001979827880859375,
  -0.037506103515625,
  -0.0263824462890625,
  -0.0267791748046875,
  0.00472259521484375,
  -0.0215911865234375,
  -0.0035114288330078125,
  -0.0038166046142578125,
  0.039337158203125,
  -0.0399169921875,
  0.004444122314453125,
  -0.00273895263671875,
  -0.0031604766845703125,
  -0.034820556640625,
  0.04071044921875,
  -0.00017654895782470703,
  -0.0025463104248046875,
  0.0419921875,
  0.0123291015625,
  0.034515380859375,
  -0.004062652587890625,
  0.012786865234375,
  -0.018524169921875,
  0.035400390625,
  0.0228729248046875,
  -0.0019369125366210938,
  0.0146026611328125,
  0.016265869140625,
  0.0203094482421875,
  -0.041107177734375,
  -0.0210113525390625,
  0.00826263427734375,
  -0.0150604248046875,
  0.01526641845703125,
  -0.0188140869140625,
  0.039886474609375,
  0.00017571449279785156,
  0.01532745361328125,
  -0.01137542724609375,
  -0.0009870529174804688,
  0.0033111572265625,
  0.007686614990234375,
  0.01099395751953125,
  0.033782958984375,

In [30]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[:500], # sometimes time out if we add all points at once
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [32]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[500:], # sometimes time out if we add all points at once
    wait=True
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

### hybrid-retrieval

In [40]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20 # why 20? limit is often 3x - 10x of k
            ),
            Prefetch(
                query=Document(
                    text=query, #bm search need actual query text
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"), # reciprocal rank fusion
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [41]:
retrieve_data("can i get a tablet", k=20)

{'retrieved_context_ids': ['B08Z3N1YTR',
  'B07Q38R2XF',
  'B0BGHMDZHG',
  'B08DNC3L4M',
  'B07ZNPPXN6',
  'B00Y1NGRM2',
  'B0788JXFXB',
  'B07L8HX46F',
  'B07KFXQFQ6',
  'B081122SFR',
  'B073R8PCB2',
  'B08DMY7S84',
  'B004M5H6D8',
  'B09KY4D7RJ',
  'B00B3507Q8',
  'B0829D5423',
  'B0BNJ1QQCM',
  'B07RW5XZSH',
  'B09G2NKNW4',
  'B08HRVCLXL'],
 'retrieved_context': ["Short Micro USB Cable,Android Charger Compatible with Fire Stick,Roku Stick,PS4,Xbox,Fast Charging Cord Compatible with Kindle Tablet,Bose SoundLink Speaker,Chromecast,Computer Phone,Power Bank,8 inch 【Short Micro USB Cable for TV Stick or Other Devcies】 8 inches Micro USB Cable is perfect lenght for charging Android phones and Windows smart phones, tablets & MP3 players, digital cameras, camcorders & more. This short Android Charger Cord is Perfect length for connect TV stick from back TV USB port. 【Fast Charging and Data Sync】22 AWG wire, charge up to 30% faster than most standard alternatives.This 8 inch short Micro USB Cable Android Charger Cord support sync data at 480 Mbps. 【Universal Compatibility】The Micro USB Cable Android Charger Cord is compatible for Bose SoundLink Speakers,Windows smart phones,tablets and other devices with micro USB port,such as PS4 ( PlayStation-4 ),Xbox Controller,Samsung Galaxy Tab,S6,Note 4,HTC One,Motorola Moto X,Sony Xperia Z3,LG G Pro 2,G Flex2,Google Nexus 6,7,Dragon Touch,HP Stream 7 Tablet,Wacom tablets. This Android charger is also compatible with Kindle Tablets, eReader,Raspberry Pi,Lonve Blue MP4,MP3 Player,Chrome Cast.Fast charging cable is compatible with Fire Stick,Roku Stick,Smart Sticks. 【Superb Durability】 The stainless steel connector heads slot in easily and steadily, and won't get loose or fall out of your devices as normal micro usb cables. With tested 1000+ bend lifespan, our android charger cable are still sturdy and strong. Flexible tangle free, which makes your life more convenient 【What You Get】1 x Short Micro-USB Charging Cable 8 inch. Micro USB Cable Connection: The cables are built with MICRO port, exclusively for the devices that has micro connectors. Please make sure you need a MICRO USB CABLE before the purchase",
  'ASURION 2 Year Tablet Accident Protection Plan ($30 - $39.99) NO ADDITIONAL COST: You pay $0 for repairs – parts, labor and shipping included. COVERAGE: Plan starts on the date of purchase. Drops, spills and cracked screens due to normal use are covered from day one. Malfunctions are covered after the manufacturer’s warranty. EASY CLAIMS PROCESS: File a claim anytime online at www.Asurion.com/Amazon or by phone. Most claims approved within minutes. We will send you an Amazon e-gift card for the purchase price of your covered product. In some cases, we will replace or repair it. EXPERT TECH HELP: Real experts are available 24/7 to help with set-up, connectivity issues, troubleshooting and much more. TERMS & DETAILS: More information about this protection plan is available within the “Product guides and documents” section. Simply click “User Guide” for more info. Asurion will also email your plan confirmation with Terms & Conditions to the address associated with your Amazon account within 24 hours of purchase (if you do not see this email, please check your spam folder). Contact us if you cannot locate your plan confirmation and Terms & Conditions via email at AmazonFeedback@Asurion.com.',
  "Hyjoy 8 inch Kids Tablet, IPS HD Display, Android 10 Tablet PC, 2GB RAM, 32GB Storage, WiFi, Bluetooth, Dual Camera, Games, Parental Control, Kidoz Installed, with Kids-Tablet Case (Blue) ✅【New Favorite for Kids】HYJOY kids tablet 8 inch is specially designed for kids and comes preinstalled with popular app FamilyGroup, has an advanced parental control password protection system, screen time setting, security modes, and surfing content management. Creates a safe, clean online environment for entertainment. ✅【FHD IPS Touch Screen & Google Play】This kids tablet has a IPS FHD touchscreen that provides an outstanding visual experience. This android tablet gives you full access to Google Play to download a large number of up-to-date educational apps. The 8 inch kids tablet LCD is designed with low blue light technology. With one click you can enter reading mode, reducing screen flicker and eye damage casued by irritating blue light. Greater comfort and safety for your kids' devices. ✅【High Performance Tablet】This mini tablet for kids is equipped with the latest version of GMS - certified Android 10.0 operating system, which is safer and faster than the Android 9.0 and eliminates unwanted ads. The 1.6 GHz quad-core processor is 20% faster than normal processors on the basic frequency. The Android kids tablet comes with 32GB RAM and expandable microSD slot (max 128G), making it easier to store e-books, songs, pictures, videos, and more! ✅【Large Capacity Battery 】The 4000mAh lithium polymer battery and low-power CPU enhance your experience and allow you to enjoy up to 6 hours of mixed reading, watching TV shows, surfing the web, and game playing. It's the perfect device for your kids to play and learn. Please note our kids tablet comes with a USB type C cable, but not a charger. Please purchase a 5V 2A charger separately. ✅【Portable Kids Tablet with Free Case】Our android tablets are slim and lightweight and fit easily in bags and backpacks, making it possible for you to take yours anywhere, anytime.The free food-grade silicone case is designed to prevent the kids tablet from damage during falls and collisions. Durable, firm, and easy to carry, this children's tablet is especially suitable for children aged 2-10. Truly a wonderful gift for birthdays, Christmas, or any holiday for your kids.",
  'NJSJ Computer Speakers, USB Powered PC Speaker, 10W Stereo Desktop Speaker with Dynamic RGB Light, Volume Control, Headphone Jack, 3.5mm AUX-in External Speaker for Laptop/Tablet/Cellphone/Monitor ♬[Hi-Fi Stereo Sound] Equipped with upgraded dual 5W drivers, uses anti-magnetic technology to suppressing static and noise. Provide high-quality audio output for you when you enjoying movies, videos, musics and games. ♬[Dynamic RGB Lighting with Touch Control] Desktop speaker alternately emit colorful RGB lighting during use, enhances the music and game dynamics experience.You can turn off the light by touch switch. ♬[USB Powered & 3.5mm Aux-in] Plug and play. The usb cable for power and aux in cable for the sound. Suitable for any device that has a standard 3.5mm headphone jack, such as desktop, laptop, cellphone, tablet, Mac, projector, Monitor, MP3, TV, echo dot, Xbox, PS4 and etc. ♬[One-Knob Control & Headphone Jack] The knob control can easily turn on/off the speaker and accurately adjust the volume. Just plug the headset into the headphone jack, then you can enjoy movies, music or gaming at late night and without disturbing your family or roommate. ♬[What You Get] NJSJ H158 RGB speaker, quick start guide. Our worry-free 24-month warranty, and lifetime friendly customer service. If our computer speaker is not compatible with your PC, laptop it can be replaced at any time.',
  'Aithney 100 PCS Stickers Funny Cute Stickers for Teens, Girls, Adults Stickers Suitable for Water Bottles, Laptop, Phone, Hydro Flask Vinyl Waterproof Aesthetic Sticker Pack ❤️【FUNNY STICKERS & PERFECT SIZE】:There are 100 different cute stickers in each pack.It is about Animals, Plants, fashion elements, Art design etc. SIZE: 2.75-4 inch. ❤️【REWARD & GIRT】: Party Favors for teens,boys,girls,women,kids etc. ❤️【Reusable and Durable】Crafted with non-marking glue, it can paste repeatedly and tear off the glue free of trace, if not satisfied, you can re-paste after tearing off. ❤️【New Update Quality】Based on the previous film, we optimize the material further to get newly upgraded color and function, which brings better performance. ❤️【Widely Application】100 pcs different stickers allows you can personalize on any items’ surface as you want, such as your hydro flask, computer, tablet, mobile phone, even your bike, motorcycle and more.',
  'Kastar 360 Swivel Rotating Stand Holder Tabletop Stand with Collapsible Base for All iPad Series: iPad1, iPad2, iPad3, iPad4, iPad Mini, iPad Air, Samsung Galaxy Tablets and 7"-10" Tablet PC (Black) Kastar Advantage: 360 degree swivel rotating stand adjusts to any angle with large compatibility of all iPad series, Samsung Galaxy Tablets and any 7"-10" Tablet PC Rotate, angle, and swivel your device for optimum viewing in any Horizontal or Vertical position at your desk?seat-back tray or airplane landscape or portrait position Easy to attach and remove, collapsible base folds for easy storage on the go. Durable and lightweight provide sturdy support for your device Perfect for reading, watching videos, typing, browsing the web--make sure you have the rubber washers lined up correctly to eliminate the wobble Include 30-day Money Back and 18-Month Manufacturer Warranty',
  'Comfyable Slim Laptop Sleeve Compatible for 15-inch MacBook Pro & 14 inch Dell Hp Lenovo Asus Chromebook Computer, Water Repellent Notebook Mac Cover Case ▶ 15 INCH CASE ⋆ - Our laptop case is compatible for new MacBook Pro 15" laptops (2016-2018 Models). Also fits ThinkPad X1 Yoga (1-4th Gen), 14 HP Acer Chromebook, New Surface Laptop 3 15 Inch 2019. Interior dimensions: 14 x 9.5 x 0.7 Inches allows for use with a wide variety of laptop and tablet models. ▶ ULTIMATE PROTECTION & SECURITY - Not all laptop cases or computer backpacks provide enough secure padding to protect your Apple MacBook. Our laptop sleeve contains superior EPE foam padding to provide good protection from slight shocks and bumps except drop-proof performance. ▶ SOFT MICROFIBER LINING & ADDITIONAL INNER COVER - This 15 inch laptop case features a protective neoprene flap in the top interior providing extra snug protection and prevents rubbing the zipper. The soft interior fleece lining our 15 inch laptop case provides a scratch free environment, so no worries that your MacBook will get scratched or damaged. ▶ MINIMAL, SLEEK & ELEGANT DESIGN - Let’s face it, everyone loves Apple\'s minimal simple and elegant design style, of course you want all of your laptop or tablet accessories to reflect that same style. That’s why our light as a feather laptop sleeve is perfect in order to protect your laptop with style',
  'Uliking Universal Case Cover for 8 inch Tablet (7.9" 8.0" 8.4" 8.5"), Flip Stand for Samsung Galaxy Tab E/4/A/S2 8.0,iPad Mini 1/2/3/4, for LG/for Asus/for HP/for Huawei/for Lenovo, Tribal Flower for 7.5-8.5 inch tablet, iPad Mini 1/2/3/4, for Samsung Galaxy Tab A 8.0 /Tab E 8.0/Tab 4 8.0/Tab S2 8.0, for Lenovo Tab 4 8 Plus, for ASUS ZenPad S 8.0, for Huawei Mediapad T1 8.0/T1 8.0 Pro/Honor T1 8.0, MediaPad M2 8.0, for Dragon Touch i8 Pro/S8/DT-M8, for xiaomi pad 2/pad 3/Mipad 4/Xiaomi Mi Pad 7.9, for VivoTab Note 8, for LG G Pad 8.0/8.3/F 8.0/X8.0/X8.3, for ASUS MeMO Pad 8; for Dell Venue 8/for Sony TAB /for HP TAB and so on. 【Durable PU Leather:】 Made from a Premium stylish PU (synthetic) leather to protect the device from scratches, damages, and shocks. (Free gift: Comes with a nice pen/stylus and soft microfiber cleaning cloth). 【Stand & Magnetic Closure:】 Fold the case for a kickstand in landscape mode and hand free for having a facetime, browsing web,watching movies and etc. Magnetic clip ensures cover is securely closed. 【Adjustable Size:】 Tension clips at four corners securely hold virtually your tablets. This clip is flexible and you can adjust the size according to the size of the tablets. (No Back Camera Opening and NOT support auto sleep/wake for any tablets due to a universal case) 【Wallet design:】 3 card slots for credit cards, photos, fitness Cards, storage/memory/SD cards, photos and a pocket for cash or note. Comes with bonus a stylus pen.',
  "BENTOBEN iPad Mini 5 Case, iPad Mini 4 Case, Slim Fit Soft Silicone Shockproof Protective Hybrid Hard PC Bumper Rugged Drop Protection Girl Women Kids Tablet Cover for iPad Mini 5/4,Purple/Mint Design ★ COMPATIABLE MODEL: BENTOBEN iPad Mini case fits for iPad Mini 5 2019 ((A2133, A2124, A2125, A2126) and iPad Mini 4 2015 (A1538, A1550), a compact and sleek silicone case, simple yet still protective and looks and feels good in your hands. ★ REASONABLE PROTECTION: Being snug fit with updated premium material and fine craftsmanship, this soft silicone design case for iPad Mini 4/5 is durable enough to protect your iPad from certain scratches and occasional drops. There’s a decent amount of lip protection and the camera is nestled in a little snug fit to stop debris and lens scratching. ★ HANDY KICKSTAND: The built-in kick stand is a great bonus when you are watching a movie, facetime, or just need to have the iPad/app in a landscape mode. And all the button features and cutouts are where they should be, leaving plenty of space around the cutouts for easy connection. ★ SLEEK & SMOOTH: The neat surface makes sliding it into/getting it out of your handbag a lot easier than other cases. All the button features and cutouts are where they should be, leaving plenty of space around the cutouts for easy connection. Highly recommend for minimalists. ★ IDEAL GIFT: Being simple and classy, it doesn't take away from the actual design of iPad, showing off the beauty of the tablet gently while offering certain protection. Ideal gift for kids, boys, girls, father, mother and friends for Birthday, Christmas Day, Anniversary Day, Valentine’s Day, etc.",
  'SAMSUNG Electronics SM-T597VZKAVZW Galaxy Tab A, 10.5", Black (WiFi & LTE Verizon) Wi-fi and LTE compatible (Verizon network only) Wide immersive Display Cinematic Dolby Atoms Surround sound Google Assistant Fast-charging',
  'GOOJODOQ Case for iPad Air 1-Smart Cover with Magnetic Auto Sleep/Wake Function PU Leather Shockproof Silicon Soft TPU Folio Case for Apple iPad Air 1 ◆◆【Exclusively Designed for iPad 10.2"】-GOOJODOQ Model A5678-10.2 keyboard case is exclusively designed for iPad 7th Gen 2019(Model Number: A2197/A2200/A2198), iPad 10.2 8th Gen 2020 (Model Number: A2270/A2428/A2429/A2430) and iPad 10.2 9th 2021 (Model Number: A2602/A2603/A2604/A2605).▲NOTE: Not compatible with any other devices. ◆◆【7 Colors Backlit and Detachable Keyboard】-The optional backlit mode consists of one white light and six RGB mixed lights, make you typing fun and easy in the dark. The bottom of the keyboard is covered with a high-end PU leather and non-slip coating that will help you maintain stability anywhere. Whether you use the keyboard alone or with a matching case,don\'t worry it would slip away. ◆◆【Built-in Apple Pencil Holder Design】-Built-in Pencil holder（for iPad）leave a slot to settle your Stylus Pen. You can slide your Apple Pencil into the holder so it doesn\'t get lost. The slot stays above the iPad for quick stylus removal when inspiration strikes,very convenient. ▲NOTE: Apple Pencil or iPad NOT included! ◆◆【Premium and Durable Leather Case】-The exterior of GOOJODOQ Keyboard Case for iPad is designed with Fingerprint-proof and Anti-scratch,Dirt resistance material, more durable. Premium leather exterior protects your tablet from accidental dropping and bumps. The interior is made of soft anti-slip fabric, which makes the keyboard and iPad more stable and protects your tablet from being scratched. The cooling hole design also helps to dissipate heat from the iPad and protect your iPad. ◆◆【Multiple Viewing Angles & Auto Sleep/ Wake Function】- With soft anti-slip fabric interior make you propping up the tablet into more different viewing angles in landscape mode. You iPad would automatically wakes or sleeps when the case is opened or closed,save much power for your iPad. The Precise cutouts allows easy access to all ports:camera, speakers, headphones Jack and Volume controls.',
  'Lenovo Tab M8 Tablet, 8" HD Android Tablet, Quad-Core Processor, 2GHz, 32GB Storage, Full Metal Cover, Long Battery Life, Android 9 Pie, ZA5G0060US, Iron Grey (Renewed) Stunning performance and stylish design combine in this quick, powerful Android tablet, 2.0 GHz processor and Android 9 Pie The stunning 8" HD (1280 x 800) display brings you a crisper and brighter image, so you can watch your favorite movies and shows without missing a detail, The modern, refined look and feel are accentuated by the full metal cover and 82% panel-to-body ratio Stay connected with built-in Bluetooth 5.0 and Wi-Fi 802.11 a/b/g/n/ac (2.4/5 GHz), Capture the moment with front and rear cameras Long-life battery – Watch or browse all day long without the need to recharge with 5000 mAh battery capacity, Product Dimensions 4.8 x 0.32 x 7.84 inches Color Iron Grey, Display Resolution Maximum',
  'Allstate 2-Year Tablet Accidental Protection Plan ($200-249.99) Coverage for product damages, breakdowns, and malfunctions Free shipping for all repairs with no deductibles or hidden fees Cancel anytime, full refund in the first 30 days. Transferable with gifts Easy online claims available 24/7',
  'AOHI 100W USB C Charger GaN+, 2 Port Type C PD Wall Charger Foldable Power Adapter with 4ft USB C to USB C LED Display Cable for MacBook Pro/Air, iPad Pro, iPhone 14/13/12, Galaxy, Laptops, Black 【100W USB C Charger with Power Delivery】AOHI USB C wall charger supports up to 100W PD fast charging during single port use, allowing fast charging for MacBook Pro 16’’ from 0% to 45% in only 30 minutes and from 0% to 100% in about 1.8 hours, providing fast and efficient charging for laptops, tablets and phones. Advanced GaN+ tech also makes our charger smaller in size and bigger in power without generating excess heat. 【Dual USB-C Ports with Intelligent Power Allocation】Using intelligent power allocation technology, the dual-port PD power adapter automatically detects and optimizes the power supply to ensure the connected devices always get the best charge, achieving high-speed charging of two devices at the same time. With this 100W PD charger, you can now fast charge two laptops or a laptop and a phone simultaneously. 【Compact Design & Multiple Safety Protection】Only 2.36*2.36*1.26inches in size and 0.44lb in weight, this GaN+ USB C fast charger features an ultra-compact, lightweight design with foldable prongs for maximum portability wherever you go, perfect for home, office and travel. Moreover, the charger is designed with over-current, over-voltage, over-heating and short-circuit protection, etc. to keep you and your devices safe. 【4ft USB C to USB C LED Display Cable Included】Our 100W USB C charger comes with a 4ft 100W USB C to USB C LED digital display cable to offer you an unparalleled visible charging experience. Equipped with E-Marker chipset for faster and safer charging, this cable features a cool LED digital screen to monitor real-time power and charging speed, and supports up to 5A, 100W PD fast charging and 480 Mbps data transfer speed. 【Wide Compatibility】The 100W USB C power adapter supports PD 18W/30W/45W/60W/65W/87W/97W/100W and is compatible with MacBook Pro/Air, iPad Pro/Air/Mini, XPS, ThinkPad, MateBook,iPhone 14/14 Pro/14 Pro Max/14 Plus, iPhone 13/13 Pro/13 Pro Max/13 Mini/12/12 Pro/12 Pro Max, Galaxy S21/S20/S10, Note 20/10+, Pixel 3XL/3/2XL, Switch, and more other USB-C laptops, tablets and phones. What You Get: 1*AOHI Magcube 100W 2-Port USB C Charger, 1*AOHI Magline 4ft USB C to USB C LED Digital Display Cable and 1*User Manual.',

In [ ]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20 # why 20? limit is often 3x - 10x of k
            ),
            Prefetch(
                query=Document(
                    text=query, #bm search need actual query text
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=models.RrfQuery(rrf=models.Rrf(weights=[3, 1])), # should be tuned, based on the data; contextual vs keyword search
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [50]:
retrieve_data("can i get a tablet device", k=20)

{'retrieved_context_ids': ['B07Q38R2XF',
  'B0BGHMDZHG',
  'B081122SFR',
  'B08DMY7S84',
  'B00Y1NGRM2',
  'B0829D5423',
  'B07L8HX46F',
  'B004M5H6D8',
  'B07YQW55CN',
  'B07RW5XZSH',
  'B08Z44LXYL',
  'B0128Z5BPI',
  'B08Y55D9JM',
  'B07FSHNRXX',
  'B00B3507Q8',
  'B00QWQQHOE',
  'B08C2DVS1V',
  'B012Q066SG',
  'B07H9NGGYR',
  'B073Y1LPJR'],
 'retrieved_context': ['ASURION 2 Year Tablet Accident Protection Plan ($30 - $39.99) NO ADDITIONAL COST: You pay $0 for repairs – parts, labor and shipping included. COVERAGE: Plan starts on the date of purchase. Drops, spills and cracked screens due to normal use are covered from day one. Malfunctions are covered after the manufacturer’s warranty. EASY CLAIMS PROCESS: File a claim anytime online at www.Asurion.com/Amazon or by phone. Most claims approved within minutes. We will send you an Amazon e-gift card for the purchase price of your covered product. In some cases, we will replace or repair it. EXPERT TECH HELP: Real experts are available 24/7 to help with set-up, connectivity issues, troubleshooting and much more. TERMS & DETAILS: More information about this protection plan is available within the “Product guides and documents” section. Simply click “User Guide” for more info. Asurion will also email your plan confirmation with Terms & Conditions to the address associated with your Amazon account within 24 hours of purchase (if you do not see this email, please check your spam folder). Contact us if you cannot locate your plan confirmation and Terms & Conditions via email at AmazonFeedback@Asurion.com.',
  "Hyjoy 8 inch Kids Tablet, IPS HD Display, Android 10 Tablet PC, 2GB RAM, 32GB Storage, WiFi, Bluetooth, Dual Camera, Games, Parental Control, Kidoz Installed, with Kids-Tablet Case (Blue) ✅【New Favorite for Kids】HYJOY kids tablet 8 inch is specially designed for kids and comes preinstalled with popular app FamilyGroup, has an advanced parental control password protection system, screen time setting, security modes, and surfing content management. Creates a safe, clean online environment for entertainment. ✅【FHD IPS Touch Screen & Google Play】This kids tablet has a IPS FHD touchscreen that provides an outstanding visual experience. This android tablet gives you full access to Google Play to download a large number of up-to-date educational apps. The 8 inch kids tablet LCD is designed with low blue light technology. With one click you can enter reading mode, reducing screen flicker and eye damage casued by irritating blue light. Greater comfort and safety for your kids' devices. ✅【High Performance Tablet】This mini tablet for kids is equipped with the latest version of GMS - certified Android 10.0 operating system, which is safer and faster than the Android 9.0 and eliminates unwanted ads. The 1.6 GHz quad-core processor is 20% faster than normal processors on the basic frequency. The Android kids tablet comes with 32GB RAM and expandable microSD slot (max 128G), making it easier to store e-books, songs, pictures, videos, and more! ✅【Large Capacity Battery 】The 4000mAh lithium polymer battery and low-power CPU enhance your experience and allow you to enjoy up to 6 hours of mixed reading, watching TV shows, surfing the web, and game playing. It's the perfect device for your kids to play and learn. Please note our kids tablet comes with a USB type C cable, but not a charger. Please purchase a 5V 2A charger separately. ✅【Portable Kids Tablet with Free Case】Our android tablets are slim and lightweight and fit easily in bags and backpacks, making it possible for you to take yours anywhere, anytime.The free food-grade silicone case is designed to prevent the kids tablet from damage during falls and collisions. Durable, firm, and easy to carry, this children's tablet is especially suitable for children aged 2-10. Truly a wonderful gift for birthdays, Christmas, or any holiday for your kids.",
  'SAMSUNG Electronics SM-T597VZKAVZW Galaxy Tab A, 10.5", Black (WiFi & LTE Verizon) Wi-fi and LTE compatible (Verizon network only) Wide immersive Display Cinematic Dolby Atoms Surround sound Google Assistant Fast-charging',
  'Lenovo Tab M8 Tablet, 8" HD Android Tablet, Quad-Core Processor, 2GHz, 32GB Storage, Full Metal Cover, Long Battery Life, Android 9 Pie, ZA5G0060US, Iron Grey (Renewed) Stunning performance and stylish design combine in this quick, powerful Android tablet, 2.0 GHz processor and Android 9 Pie The stunning 8" HD (1280 x 800) display brings you a crisper and brighter image, so you can watch your favorite movies and shows without missing a detail, The modern, refined look and feel are accentuated by the full metal cover and 82% panel-to-body ratio Stay connected with built-in Bluetooth 5.0 and Wi-Fi 802.11 a/b/g/n/ac (2.4/5 GHz), Capture the moment with front and rear cameras Long-life battery – Watch or browse all day long without the need to recharge with 5000 mAh battery capacity, Product Dimensions 4.8 x 0.32 x 7.84 inches Color Iron Grey, Display Resolution Maximum',
  'Kastar 360 Swivel Rotating Stand Holder Tabletop Stand with Collapsible Base for All iPad Series: iPad1, iPad2, iPad3, iPad4, iPad Mini, iPad Air, Samsung Galaxy Tablets and 7"-10" Tablet PC (Black) Kastar Advantage: 360 degree swivel rotating stand adjusts to any angle with large compatibility of all iPad series, Samsung Galaxy Tablets and any 7"-10" Tablet PC Rotate, angle, and swivel your device for optimum viewing in any Horizontal or Vertical position at your desk?seat-back tray or airplane landscape or portrait position Easy to attach and remove, collapsible base folds for easy storage on the go. Durable and lightweight provide sturdy support for your device Perfect for reading, watching videos, typing, browsing the web--make sure you have the rubber washers lined up correctly to eliminate the wobble Include 30-day Money Back and 18-Month Manufacturer Warranty',
  "Samsung Galaxy Tab A 8.0-Inch 32GB Wi-Fi Android 9.0 Pie Tablet (Black) (Renewed) DISPLAY: See more of your favorite content on the Galaxy Tab A 8.0-inch screen with minimized bezels for maximum view-ability. And with a lightweight, durable design, you can take your view around the house or on the go BATTERY LIFE: Galaxy Tab A carries more power than you'd expect in a device this sleek. The 5,100mAh battery gives you the freedom to forget about your charger for long periods of time when you have somewhere to go or lots to watch STORAGE: Keep all your favorite stuff close at hand including songs, photos, videos and more with 32GB internal memory and up to an extra 512GB of expandable memory with external microSD card IMPRESSIVE CAMERAS: Take crisp, captivating photos with the rear-facing 8MP camera, or look stunning in selfies and video chats with the front-facing camera This Certified Refurbished product is backed by a 90-day warranty",
  'Uliking Universal Case Cover for 8 inch Tablet (7.9" 8.0" 8.4" 8.5"), Flip Stand for Samsung Galaxy Tab E/4/A/S2 8.0,iPad Mini 1/2/3/4, for LG/for Asus/for HP/for Huawei/for Lenovo, Tribal Flower for 7.5-8.5 inch tablet, iPad Mini 1/2/3/4, for Samsung Galaxy Tab A 8.0 /Tab E 8.0/Tab 4 8.0/Tab S2 8.0, for Lenovo Tab 4 8 Plus, for ASUS ZenPad S 8.0, for Huawei Mediapad T1 8.0/T1 8.0 Pro/Honor T1 8.0, MediaPad M2 8.0, for Dragon Touch i8 Pro/S8/DT-M8, for xiaomi pad 2/pad 3/Mipad 4/Xiaomi Mi Pad 7.9, for VivoTab Note 8, for LG G Pad 8.0/8.3/F 8.0/X8.0/X8.3, for ASUS MeMO Pad 8; for Dell Venue 8/for Sony TAB /for HP TAB and so on. 【Durable PU Leather:】 Made from a Premium stylish PU (synthetic) leather to protect the device from scratches, damages, and shocks. (Free gift: Comes with a nice pen/stylus and soft microfiber cleaning cloth). 【Stand & Magnetic Closure:】 Fold the case for a kickstand in landscape mode and hand free for having a facetime, browsing web,watching movies and etc. Magnetic clip ensures cover is securely closed. 【Adjustable Size:】 Tension clips at four corners securely hold virtually your tablets. This clip is flexible and you can adjust the size according to the size of the tablets. (No Back Camera Opening and NOT support auto sleep/wake for any tablets due to a universal case) 【Wallet design:】 3 card slots for credit cards, photos, fitness Cards, storage/memory/SD cards, photos and a pocket for cash or note. Comes with bonus a stylus pen.',
  'Allstate 2-Year Tablet Accidental Protection Plan ($200-249.99) Coverage for product damages, breakdowns, and malfunctions Free shipping for all repairs with no deductibles or hidden fees Cancel anytime, full refund in the first 30 days. Transferable with gifts Easy online claims available 24/7',
  'Batyue Case for Samsung Galaxy Tab S5e 10.5" 2019 Model SM-T720/T725, [360° Swivel Kickstand/Leather Hand Strap] Kids Heavy Duty Shockproof Rugged Full Body Drop Protection Case for Students, Red 【COMPATIBILITY】This rugged shockproof case ONLY designed for Samsung Galaxy Tab S5e 10.5 2019 (Model: SM-T720/SM-T725). DO NOT fit any other models. Please check the model# on the back of your tablet before purchase. 【KIDS CHILD PROOF CASE】Advanced 3 in 1 construction with premium PC and shock-absorbing TPU material offers comprehensive protection for your tablet; Perfect case for children and against accidental drop, shock, bumps and skid. Full access to all ports, buttons and cameras without removing the case. 【360° ROTATABLE KICKSTAND】The sturdy 360 degrees rotating foldable kickstand provides flexible and comfortable angles viewing when watching videos, texting, gaming, eating or learning etc. Ideal for kids, students, children. NOTE: NO built-in screen protector to keep the iPad screen original touch feeling. 【LEATHER HAND STRAP】The leather handle hand grip in the back allows you to hold your tablet securely with one hand. Convenient for teachers, doctors, engineers, outdoor workers or anyone else who needs it for teaching training, medical diagnosing, construction supervising, restaurant ordering, conference demonstrating, etc. 【Customer Service】- BATYUE customer team would endeavor to win 100% customer satisfaction. If you meet any question, please contact us, we will fix your issue within 24 hours.',
  'Benazcap Case for All New 7 Inch Tablet 2019, Folio Stand Smart Cover for 7 Inch 2019 Tablet (9th Gen) with Auto Sleep/Wake, Historical Imprint Made from durable PU (synthetic) leather with soft microfibers to protect your screen from dust and scratches and provide an extra layer of protection. The case is easy to install and remove, covering the edge of the Tablet and protecting it from damage. Powerful magnets keep the front cover sealed. Precise incision, easy access to buttons, ports, and cameras. Support auto Sleep / Wake function. Slim design, has flip capability to transform the case into a horizontal viewing stand, Provides support for two angles, comfortable viewing. Built in leather hand strap for comfortable one-handed use. Externally added elastic closure strap which adds to the magnetic closure to keep the case closed and the device protected when not in use. And added elastic pencil holder (stylus NOT included). Specifically designed for All-New Tablet 7-inch (9th generation, 2019 Release). The Case will NOT FIT Tablet 7 (7th Gen 2017 Release / 5th Gen 2015 Release ). 1 x Thanks / Warranty Card for worry-free guarantee.',
  'GOZOPO Kids Case for Lenovo Tab M10 Plus and Lenovo M10 FHD Plus (2nd Gen) 10.3" Tablet TB-X606F/X606X, with Shoulder Strap and Kickstand Shockproof Protective Case (Blue) 【Compatibility】ONLY Compatible with Lenovo M10 FHD Plus TB-X606F (10.3") / Lenovo Smart Tab FHD M10 Plus (2nd Gen) TB-X606F 10.3 Inch 2020 Released, ** NOTE ** DO NOT FIT ANY OTHER MODELS. if you can not 100% confirm your tablet model, please feel free to Send E-mail to contact us. we will help you to confirm and solve your problems as soon as possible 【Excellent Protection - Sturdy and easy to carry ! 】- It is made of imported EVA environmental protection and child friendly non-toxic EVA foam material, efficiently prevents your tablet from accidental drops, bumps and scratches ! 【Unique Spider web Design Appearance - Support multi-angle standing 】To create concise aesthetic feeling with meticulous thinking and exquisite workmanship. The back kickstand can also be folded out into a viewing stand in landscape position - 360° Swiveling stand can be freely retracted and foldable. Ideal for kids, Students, Teachers or anyone else who needs it for presentations, conferences and travelling. 【Adjustable & Detachable New Carrying Strap】 Portable Shoulder Strap allows to carry your tablet in landscape/portrait mode securely in outdoors or hang your tablet in kitchen,bedroom,car seat for convenient usage -- Attach strap to any two holes ! 【Customer Service】if our product have defective in any way when you received, Or if you need anything help - such as replacement,refund,installation guide or skills of function using. please feel free to Send E-mail to contact us. we will solve your problems to ensure your complete satisfaction within 24 hours.',
  "RCA Pro 10 with WiFi 10.1' Touchscreen 16GB Tablet PC Featuring Android 4.4 KitKat Operating System with Folio Keyboard (Renewed) ",
  'for ONN surf 8" Tablet Gen 2 100011885 2APUQW829 Touch Screen Digitizer Replacement Compatibility: Compatible with For ONN surf 8" Tablet Gen 2 100011885 2APUQW829 Touch Screen Digitizer High Quality: 100% brand new, each item has been tested and in good condition before shipping. Installation: Easy to install, perfect replacement for your damaged, cracked, marked, dirty or non-functioning digitizer TouchScreen. Package: 1*pcs digitizer TouchScreen panel, 1*set operation tools. Return Guarantee: One year warranty. For any reason you\'re not completely satisfied with the product, you can ask for a replacement or full refund.',
  'Uliking Universal 9.5-10.5 inch Andriod iOS Tablets Case, Bling Glitter Folio Stand Cover for 9.6" 9.7" 10.1" 10.5", Fire HD 10/iPad Air 1 2/iPad 9.7 2017 2018/iPad Pro 9.7/10.5 & Others, Rosegold The universal 10 inch tablet case; fits Amazon Fire HD 10 2015 & 2017, iPad 2/3/4, New iPad 9.7 2017 2018, iPad Air 2, iPad Air 1, iPad pro 9.7 2016; ipad pro 10.5; Galaxy Tab S2 9.7; Samsung Galaxy Tab 3 10.1/ Tab 4 10.1/ Tab S3 9.7/ Tab A 9.7/ Tab E 9.6, Huawei MediaPad T3 10, Huawei MediaPad M3 Lite 10, Asus ZenPad 3S 10 Z500M 9.7, Lenovo Tab 2 A10-70, Tab 2 A10-30(TB2-X30F), Lenovo Tab 4 10 PLUS, UK 10.1" Quad Coreand other 9.5 - 10.5 in tablets. 【 PU Leather :】made from durable PU (synthetic) leather to protect the device from scratches, damages, and shocks. (Free gift: Comes with a nice pen/stylus and soft microfiber cleaning cloth). 【Multiple Vewing Stand Angles:】 Front cover can be folded, convenient for reading, watching movies, playing games and browsing the web. 2 anti-slip stripes allow you to set up multiple horizontal stand angles, stay stable. Built-in magnet keeps the magnetic button closed, no need to worry about accidental opening. 【Stable Structure:】Tension clips at four corners securely hold virtually your tablets PC. Precise cut outs, full access to all features ,Speaker, Ports and Buttons,(No Back Camera Opening) 【Card Slots:】 PU leather case with built-in 3 cards holder, convenient for storing your various cards, photos; (Auto Sleep/Wakeup is not supported and no camera opening because it is a universal case).',
  'Generic Nextbook 8" Android Tablet Case with USB Keyboard for Nextbook 8 (Tablet Case Black) Please note!!!! Do not order unless you have the brands in the title. The keyboard does not work with any other brands Works with next Book 8 only!!!!!!! Great PU material, soft and comfortable, no peeling With a card stand to support tablet PC You can put your tablet PC on desk with this leather Case Keyboard and USB interface design, come with Stylus Works with nextbook 8 Support device dimension: Fit tablet length: 180 230 mm Works With Nextbook 8 With a card stand to support tablet PC Keyboard and usb interface design, come with stylus Support device dimension: Fit tablet length: 180 ~ 230 mm Fit tablet width: 135 ~ 168 mm Fit tablet depth: 8 ~ 17 mm',
  'Apple iPad Air 2 Wi-Fi, 9.7" Tablet, 16 GB, GOLD (MH0W2LL/A) 9.7-Inch Retina Display Touch ID fingerprint sensor ATX chip 8Mp insight camera FaceTime HD camera',
  'All-New HD 8 2020 Tablet Case, HD 8 Plus 2020 Case, JZCreater Folio PU Leather Smart Case Cover with Auto Wake/Sleep （Not Fit HD 8 Old Versions Prior to 2018）, Sea Island Specifically Designed: Only Compatible with All-New HD 8 10th Generation - 2020 released (HD 8 2020 and HD 8 Plus 2020 , 8inch Display, tablet size is 8.0" x 5.4" x 0.4". Please check your tablet model and size before purchase. NOTE: NOT Fits HD 8 generations prior to 2018 (2016 2017 2018 Versions, 8th/7th/6th Gen ) , 7 inch Fire 7 Tablet and 10inch HD 10 Tablet. Interior Card Slots & Cash Holder: Built-in card slots and have a photo / money pocket to put your business cards/ bank cards and so on. Easy to insert and remove, which will bring more convenient in daily life. Multi-Angle Standing: This multifunction cover is uniquely designed to flip back and transform the case into a comforGalaxy Table viewing stand, this capability allows the viewer to use the Galaxy Tablet hands-free whatever your position. Easy and comforGalaxy Table to enjoy typing, video chat and video viewing. 360 Degree Protection: There are full-coverage protection (with durable PU leather cover and soft silicone gel interior) to prevent scratches, dust, fingerprints or other daily damage. And easy to clean through mopping or brushing due to smooth surface. 100% SATISFACTION GUARANTEE - Your satisfaction is our guarantee! If you aren\'t satisfied with the item for ANY reason within 180 days of purchase, we will refund the full purchase price.',
  '2-Year Protection Plan plus Accident Protection for Fire HD 10 Tablet (2015 release) (delivered via e-mail) Your Protection Plan will be delivered via email as soon as the device ships Only Compatible with Fire HD 10 (5th Generation, 2015 release) purchased within the last 30 days Your card will be charged immediately, plan starts when device is delivered Receive a replacement device 2 to 3 days after you make a valid claim Make up to 3 claims during the term of your warranty Cancel anytime, full refund in first 90 days Fully transferable with gifts No deductibles or shipping fees',
  "SEYMAC Stock Galaxy Tab A 10.5 Case, SM-T590/ T595/ T597, Full-Body [Heavy Duty] & [Shock Proof] Armor Protective Case with Stand & Shoulder Strap for Samsung Tab A 10.5 Inch 2018 (Gray+Black) Compatible Models: It’s only fit for Samsung Galaxy Tab A 10.5 Case (2018) SM-T590/SM-T595, NOT fit other models, please confirm the model before purchase. Please kind note: There is NO built in screen protector on the case. Full Body Protection: Three layer design features a silicone and thermoplastic polycarbonate provides protection against accident drops, shock and bumps,shockproof, shock resistant,heavy duty protection. Convenient kickstand: Built in kick-stand feature for landscape viewing to enjoy your Tablet hand-free,it's convenience for video chatting/typing/ watching movies or have a face time.And it’s allows easy access to all buttons, controls and ports. Portable Shoulder Strap: Adjustable portable shoulder straps that you can carry your Tablet for outside/travelling/climbing. It is easy to attach and remove ,it can use together or separate or hang from anywhere for your better entertainment. SEYMAC Stock Seller Service: Fit for outdoor activists,free charge of Product Changing or Refunding after received products within 3 months & 6 months warranty and maintenance of SEYMAC Stock commodity.",
  'Transwon Kids Case for Dragon Touch K10 Tablet, Dragon Touch Notepad K10 Tablet Case, MARVUE Pad M20 Tablet 10.1 Inch Tablet Case, LUSS 10 Inch Tablet Case, TenYiDe 10.1 Tablet Case - Black '],
 'similarity_scores': [0.75000006,
  0.59999996,
  0.5,