In [2]:
import pandas as pd
import openai
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct

### read sample dataset

In [11]:
df_items = pd.read_json('../../data/raw/meta_Electronics_2022_2023_ratings_100_sample_1000.jsonl', lines=True)

In [12]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Computers,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,4.5,153,[Specifically Designed For: Samsung Galaxy Tab...,[Specifically design for Samsung Galaxy Tab E ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Leafbook,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7 Inches', '...",B01DJI7TP8,NaN,NaN,NaN
1,All Electronics,Lume Cube AIR Video Conference Lighting Kit - ...,3.7,215,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],LUME CUBE,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '1.61 x 1.61 x 1.1 inch...,B07M6SWKLT,NaN,NaN,NaN
2,All Electronics,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,4.5,1278,[Insanely good 360˚ sound - Ultimate Ears Boom...,[Ultimate Ears boom 2 is the 360-degree wirele...,68.49,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'HONEST review of the UE Boom 2 spe...,Ultimate Ears,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '2.75 x 2.75 x 7.08 inc...,B07J31M7PW,NaN,NaN,NaN
3,All Electronics,Seagate FreeAgent GoFlex TV STAJ100,3.5,108,[Watch streaming media directly from the Inter...,"[Product Description, The Seagate GoFlex TV HD...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Seagate,"[Electronics, Television & Video, Streaming Me...","{'Brand Name': 'Seagate', 'Item Weight': '10.7...",B003IT6YFK,NaN,NaN,NaN
4,All Electronics,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",4.5,110,[🎧【High-quality Stereo Sound】Built-in multiple...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'J&D 2RCA Male to 2RCA Male Cable',...",JSAUX,"[Electronics, Television & Video, Accessories,...",{'Package Dimensions': '10.16 x 3.15 x 0.71 in...,B099ZPY68J,NaN,NaN,NaN

In [7]:
list(df_items['features'].values)[0]

["Specifically Designed For: Samsung Galaxy Tab 3 Lite 7.0 7'' T110 T111 Tablet / Galaxy Tab E Lite 7.0 (NOT FIT FOR Samsung Galaxy Tab 3 7.0 T210)",
 'Premium PU leather exterior and microfiber interior. Ultra slim and lightweight hard back design adds minimal bulk while protecting your precious device.',
 'Precise cut-outs and openings for easy access to all tablet features.',
 'Cover has flip capability to transform the case into a viewing stand and keyboard stand. One piece case, the front and back does not separate.',
 'Various colors are available.Magnetic closure.']

In [8]:
list(df_items['images'].values)[0]

[{'thumb': 'https://m.media-amazon.com/images/I/51PML408loL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51PML408loL._AC_.jpg',
  'variant': 'MAIN',
  'hi_res': 'https://m.media-amazon.com/images/I/719i+AMvocL._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51lclDdsfZL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51lclDdsfZL._AC_.jpg',
  'variant': 'PT01',
  'hi_res': 'https://m.media-amazon.com/images/I/61H-oKcUr0L._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51X5YjAc9mL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51X5YjAc9mL._AC_.jpg',
  'variant': 'PT02',
  'hi_res': 'https://m.media-amazon.com/images/I/61djvW-muYL._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51TPrYSPW8L._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51TPrYSPW8L._AC_.jpg',
  'variant': 'PT03',
  'hi_res': 'https://m.media-amazon.com/images/I/61kRGWeGHjL._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51hxe5FLRXL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51hxe5FLRXL._AC_.jpg',
  'variant': 'PT04',
  'hi_res': 'https://m.media-amazon.com/images/I/61HQnF7WQrL._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51iKHXHr+qL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51iKHXHr+qL._AC_.jpg',
  'variant': 'PT05',
  'hi_res': 'https://m.media-amazon.com/images/I/61A5von8BmL._AC_SL1000_.jpg'},
 {'thumb': 'https://m.media-amazon.com/images/I/51jEverI8ZL._AC_US40_.jpg',
  'large': 'https://m.media-amazon.com/images/I/51jEverI8ZL._AC_.jpg',
  'variant': 'PT06',
  'hi_res': 'https://m.media-amazon.com/images/I/71a9NwAb7oL._AC_SL1000_.jpg'}]

### preprocess titles and features 
want one single text to descripe the item

In [13]:
def preprocess_item(row):
    return f'{row["title"]} {" ".join(row["features"])}'

def extract_first_large_image(row):
    return row['images'][0].get('large', "")

In [14]:
df_items['preprocessed_description'] = df_items.apply(preprocess_item, axis=1)
df_items['image'] = df_items.apply(extract_first_large_image, axis=1)
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,Computers,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,4.5,153,[Specifically Designed For: Samsung Galaxy Tab...,[Specifically design for Samsung Galaxy Tab E ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Leafbook,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7 Inches', '...",B01DJI7TP8,NaN,NaN,NaN,Galaxy Tab E Lite 7.0 Case - Leafbook Slim Lig...,https://m.media-amazon.com/images/I/51PML408lo...
1,All Electronics,Lume Cube AIR Video Conference Lighting Kit - ...,3.7,215,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],LUME CUBE,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '1.61 x 1.61 x 1.1 inch...,B07M6SWKLT,NaN,NaN,NaN,Lume Cube AIR Video Conference Lighting Kit - ...,https://m.media-amazon.com/images/I/411wKstRw1...
2,All Electronics,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,4.5,1278,[Insanely good 360˚ sound - Ultimate Ears Boom...,[Ultimate Ears boom 2 is the 360-degree wirele...,68.49,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'HONEST review of the UE Boom 2 spe...,Ultimate Ears,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '2.75 x 2.75 x 7.08 inc...,B07J31M7PW,NaN,NaN,NaN,Ultimate Ears BOOM 2 Portable Waterproof & Sho...,https://m.media-amazon.com/images/I/41kYEBxNW2...
3,All Electronics,Seagate FreeAgent GoFlex TV STAJ100,3.5,108,[Watch streaming media directly from the Inter...,"[Product Description, The Seagate GoFlex TV HD...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Seagate,"[Electronics, Television & Video, Streaming Me...","{'Brand Name': 'Seagate', 'Item Weight': '10.7...",B003IT6YFK,NaN,NaN,NaN,Seagate FreeAgent GoFlex TV STAJ100 Watch stre...,https://m.media-amazon.com/images/I/31Vy2ogKvD...
4,All Electronics,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",4.5,110,[🎧【High-quality Stereo Sound】Built-in multiple...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'J&D 2RCA Male to 2RCA Male Cable',...",JSAUX,"[Electronics, Television & Video, Accessories,...",{'Package Dimensions': '10.16 x 3.15 x 0.71 in...,B099ZPY68J,NaN,NaN,NaN,"JSAUX RCA Cable（10ft/3M, RCA Audio Cable Shiel...",https://m.media-amazon.com/images/I/41EbtDHhNE...

### sample 50 items from dataset

In [16]:
df_sample = df_items.sample(50, random_state=42)
df_sample.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
521,All Electronics,"Laxihub Indoor Home Security Camera, P2 Baby M...",4.0,6459,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Laxihub P2 1080p Indoor Wireless C...,LAXIHUB,"[Electronics, Camera & Photo, Video Surveillan...",{'Package Dimensions': '6.61 x 5.51 x 3.11 inc...,B08THC8HPD,NaN,NaN,NaN,"Laxihub Indoor Home Security Camera, P2 Baby M...",https://m.media-amazon.com/images/I/51xQLCPORo...
737,Camera & Photo,"Neewer NW-760 HD Monitor, IPS 7"" for Sony Cano...",4.3,454,[High Contrast: 1200:1; High Resolution: Full ...,"[Note:Camera,Tripod and battery are not includ...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Neewer,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '8.8 x 2.6 x 7.7 inches...,B01LWYDXNF,NaN,NaN,NaN,"Neewer NW-760 HD Monitor, IPS 7"" for Sony Cano...",https://m.media-amazon.com/images/I/51HQM5o0yj...
740,Industrial & Scientific,4 Pack Replacement 3.5mm Male Plug to Bare Wir...,4.4,138,[4 Pack 12in Replacement 3.5mm male plug conne...,[4 Pack Replacement 3.5mm Male Plug to Bare Wi...,5.97,[{'thumb': 'https://m.media-amazon.com/images/...,[],Accessonico,"[Electronics, Home Audio, Home Audio Accessori...","{'Brand': 'Accessonico', 'Connector Type': 'Au...",B08DR4K78X,NaN,NaN,NaN,4 Pack Replacement 3.5mm Male Plug to Bare Wir...,https://m.media-amazon.com/images/I/41rbB+pFJE...
660,All Electronics,Samsung LN40A650 40-Inch 1080p 120Hz LCD HDTV ...,4.1,437,"[Touch of Color Bezel, Full HD 1080p Resolutio...","[Product description, Samsung 40"" 1080p LCD HD...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],SAMSUNG,"[Electronics, Television & Video, Televisions,...","{'Brand Name': 'SAMSUNG', 'Item Weight': '37.5...",B0014175NE,NaN,NaN,NaN,Samsung LN40A650 40-Inch 1080p 120Hz LCD HDTV ...,https://m.media-amazon.com/images/I/312u2KwkRL...
411,All Electronics,"GE UltraPro 6 Outlet Surge Protector, 2 ft Des...",4.7,2301,[Power more - Expand the reach of your outlet ...,[Connect your devices confidently and convenie...,9.88,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '6 Outlet Surge Protector (Home Off...,GE,"[Electronics, Television & Video, Accessories,...","{'Manufacturer': 'Jasco Products Company, LLC'...",B08DLDCJQR,NaN,NaN,NaN,"GE UltraPro 6 Outlet Surge Protector, 2 ft Des...",https://m.media-amazon.com/images/I/41Bt6VJ6om...

### define embedding function

openai: https://developers.openai.com/api/docs/guides/embeddings

In [18]:
response = openai.embeddings.create(input="Random Text", model='text-embedding-3-small')
len(response.data[0].embedding)

1536

In [24]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(input=text, model=model)
    return response.data[0].embedding

### create qdrant collection

In [21]:
qdrant_client = QdrantClient(url = "http://localhost:6333")

In [22]:
qdrant_client.create_collection(
    collection_name="amazon-electronics-items-collection-01",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

### add data to qdrant

True

### embed data
need to create point struct, to ingest into qdrant

In [ ]:
# example
pointstruct = PointStruct(
    id = 0,
    vector = get_embedding("hello world"),
    payload  = {"text": "hello world", "mdoel": "text-embedding-3-small"}
)

In [29]:
pointstruct

PointStruct(id=0, vector=[-0.006793975830078125, -0.0391845703125, 0.03411865234375, 0.0287322998046875, -0.024810791015625, -0.0419921875, -0.030303955078125, 0.049346923828125, -0.013946533203125, -0.0177001953125, 0.01537322998046875, -0.0269775390625, -0.0209808349609375, -0.027801513671875, 0.0086212158203125, 0.03570556640625, -0.053680419921875, -0.0023174285888671875, 0.008819580078125, 0.048065185546875, 0.037109375, -0.00922393798828125, -0.00875091552734375, 0.01140594482421875, 0.01410675048828125, -0.0021686553955078125, -0.037567138671875, 0.045440673828125, 0.01125335693359375, -0.039642333984375, 0.0234222412109375, -0.05059814453125, 0.01203155517578125, -3.224611282348633e-05, 0.016021728515625, 0.006099700927734375, 0.031951904296875, 0.0034084320068359375, -0.00860595703125, -0.01058197021484375, -0.037384033203125, -0.03448486328125, 0.050048828125, 0.0193634033203125, -0.01432037353515625, 0.0153045654296875, -0.0543212890625, 0.050445556640625, 0.04541015625, 0.05377197265625, -0.0015516281127929688, 0.0185394287109375, 0.035614013671875, 0.11590576171875, -0.0132598876953125, -0.040924072265625, 0.01336669921875, 0.047760009765625, -0.0149688720703125, 0.0246429443359375, 0.0322265625, 0.01336669921875, 0.0170135498046875, 0.024810791015625, 0.01332855224609375, 0.00896453857421875, -0.0244293212890625, -0.0003771781921386719, -0.0006184577941894531, 0.053863525390625, -0.0024871826171875, 0.037750244140625, -0.018646240234375, -0.01152801513671875, -0.035125732421875, -0.0113372802734375, -0.03668212890625, 0.004169464111328125, 0.01532745361328125, -0.05230712890625, -0.03436279296875, 0.005382537841796875, -0.0214691162109375, -0.06292724609375, -0.01241302490234375, 0.0303802490234375, -0.046478271484375, 0.0028324127197265625, -0.0015230178833007812, -0.036956787109375, 0.01317596435546875, 0.01450347900390625, 0.0005784034729003906, 0.043212890625, 0.0233612060546875, 0.0099639892578125, -0.00977325439453125, 0.0418701171875, 0.062744140625, -0.006015777587890625, 0.038665771484375, -0.02471923828125, 0.02197265625, -0.0028591156005859375, 0.0260162353515625, 0.034149169921875, -0.01221466064453125, -0.04742431640625, -0.03302001953125, 0.024017333984375, -0.11761474609375, -0.00021958351135253906, -0.0121002197265625, -0.039031982421875, 0.006343841552734375, 0.056121826171875, 0.08880615234375, -0.07427978515625, 0.0207366943359375, -0.047119140625, 0.029205322265625, -0.0122222900390625, -0.0207366943359375, -0.046112060546875, -0.071044921875, -0.0127410888671875, -0.01305389404296875, 0.041229248046875, -0.0362548828125, -0.005092620849609375, 0.01453399658203125, 0.030853271484375, 0.00101470947265625, -0.017578125, -0.023681640625, 0.00850677490234375, -0.052276611328125, -0.01496124267578125, -0.0272674560546875, 0.053131103515625, 0.067138671875, -0.035400390625, -0.00440216064453125, -0.0303192138671875, -0.00388336181640625, -0.0286102294921875, -0.0159912109375, 0.0404052734375, -0.0111236572265625, 0.002796173095703125, 0.029327392578125, 0.03839111328125, -0.060089111328125, 0.020782470703125, 0.004184722900390625, 0.007083892822265625, 0.0303192138671875, -0.040985107421875, -0.006977081298828125, 0.03216552734375, 0.0028820037841796875, 0.004608154296875, -0.060546875, -0.008209228515625, -0.01324462890625, -0.006542205810546875, -0.02069091796875, 0.00177001953125, -0.04461669921875, 0.0027713775634765625, 0.010498046875, -0.0024433135986328125, -0.032196044921875, -0.044525146484375, 0.0157623291015625, 0.00521087646484375, 0.031982421875, -0.058746337890625, -0.03009033203125, -0.033233642578125, 0.054046630859375, 0.069580078125, 0.0111236572265625, 0.0023651123046875, -0.0338134765625, -0.01409149169921875, 0.0170440673828125, -0.013519287109375, 0.0101165771484375, 0.02215576171875, -0.04449462890625, 0.0640869140625, 0.03106689453125, 0.0037288665771484375, 0.002269744873046875, -0.03729248046875, 0.0841064453125, 0.021453857421875, -0.01513671875, 0.03631591796875, -0.0018625259399414062, -0.011016845703125, -0.0281219482421875, -0.0165252685546875, -0.021881103515625, -0.026824951171875, -0.006122589111328125, 0.0633544921875, 0.00620269775390625, -0.034210205078125, 0.058349609375, -0.005519866943359375, -0.0345458984375, -0.004398345947265625, -0.0253143310546875, -0.0007605552673339844, 0.041229248046875, 0.0116729736328125, 0.01059722900390625, -0.0408935546875, -0.044921875, 0.0850830078125, 0.07159423828125, -0.0171661376953125, 0.032867431640625, -1.609325408935547e-05, 0.0206298828125, 0.00762939453125, 0.040618896484375, 0.02716064453125, 0.026214599609375, 0.0160675048828125, 0.03131103515625, -0.044952392578125, -0.0023059844970703125, -0.01007843017578125, 0.037322998046875, -0.0218048095703125, -0.021331787109375, -0.0089263916015625, -0.0433349609375, 0.01146697998046875, 0.0214385986328125, 0.0147857666015625, 0.0335693359375, -0.0258026123046875, -0.019439697265625, -0.0268096923828125, -0.004207611083984375, 0.01383209228515625, 0.00807952880859375, 0.055755615234375, -0.006381988525390625, -0.005107879638671875, 0.028411865234375, -0.006214141845703125, -0.01338958740234375, -0.00464630126953125, 0.07489013671875, -0.014862060546875, -0.03729248046875, -0.048980712890625, -0.026947021484375, -0.03802490234375, -0.0455322265625, -0.0264739990234375, -0.0014438629150390625, -0.01032257080078125, 0.0157928466796875, -0.00922393798828125, 0.039825439453125, -0.021453857421875, 0.060272216796875, -0.038482666015625, -0.00188446044921875, 0.005130767822265625, 0.016510009765625, -0.00618743896484375, -0.020111083984375, 0.009613037109375, -0.019073486328125, 0.0012083053588867188, -0.004344940185546875, 0.018707275390625, -0.0452880859375, 0.00211334228515625, 0.03765869140625, 0.0005898475646972656, 0.036712646484375, -0.006191253662109375, 0.01995849609375, 0.036346435546875, 0.0297393798828125, 0.0010766983032226562, -9.590387344360352e-05, 0.0207977294921875, 0.01983642578125, 0.0013265609741210938, 0.0237579345703125, -0.052459716796875, 0.06353759765625, -0.01432037353515625, -0.004608154296875, 0.0267181396484375, -0.00897216796875, 0.0288848876953125, 0.032440185546875, -0.0550537109375, 0.05047607421875, 0.017913818359375, -0.037628173828125, 0.029266357421875, 0.040283203125, 0.003269195556640625, -0.0006084442138671875, -0.048095703125, 0.001247406005859375, -0.03094482421875, 0.00022232532501220703, -0.052337646484375, 0.0284271240234375, -0.04461669921875, -0.0215911865234375, 3.74913215637207e-05, 0.020477294921875, -0.0060272216796875, 0.042205810546875, -0.00637054443359375, -0.021453857421875, -0.003986358642578125, -0.0185546875, -0.04937744140625, -0.004962921142578125, 0.0119781494140625, 0.01020050048828125, -0.004955291748046875, -0.039398193359375, 0.029632568359375, -0.006488800048828125, 0.02716064453125, -0.031280517578125, -0.0274505615234375, 0.0160980224609375, -0.0107421875, -0.01776123046875, 0.00148773193359375, 0.05926513671875, -0.04443359375, 0.00788116455078125, -0.0107269287109375, -0.00814056396484375, 0.01715087890625, -0.0015745162963867188, -0.0171661376953125, 0.0136260986328125, -0.024261474609375, 0.0221405029296875, -0.0173797607421875, -0.01129913330078125, 0.047119140625, -0.0255889892578125, -0.0290985107421875, 0.0021038055419921875, -0.00588226318359375, 0.048126220703125, 0.0156097412109375, -0.023712158203125, -0.060546875, 0.018280029296875, 0.043060302734375, 0.0005917549133300781, 0.005466461181640625, 0.0258331298828125, -0.0113677978515625, -0.04656982421875, -0.032684326171875, 0.004833221435546875, 0.007415771484375, 0.045654296875, -0.0081787109375, 0.01000213623046875, -0.02276611328125, -0.011260986328125, -0.022796630859375, 0.0038318634033203125, -0.0011539459228515625, 0.02081298828125, 0.00585174560546875, 0.0008349418640136719, -0.0308837890625, 0.08074951171875, -0.0279998779296875, 0.0184478759765625, 0.009490966796875, 0.018798828125, -0.0298919677734375, -0.0026912689208984375, -0.00013208389282226562, -0.0173797607421875, -0.0196685791015625, 0.0316162109375, -0.0313720703125, 0.017669677734375, 0.0007948875427246094, -0.052154541015625, -0.032958984375, -0.01418304443359375, 0.03192138671875, 0.01248931884765625, -0.0202178955078125, 0.007442474365234375, -0.022796630859375, 0.034637451171875, 0.033935546875, -0.037353515625, -0.0175628662109375, -0.00974273681640625, -0.03472900390625, -0.00754547119140625, 0.006778717041015625, 0.01244354248046875, 0.022705078125, -0.017486572265625, 0.034454345703125, -0.03289794921875, 0.058929443359375, 0.057769775390625, -0.0184173583984375, 0.0242462158203125, -0.07080078125, -0.022247314453125, -0.01113128662109375, -0.04302978515625, 0.0026111602783203125, 0.01291656494140625, -0.036102294921875, -0.0016107559204101562, 3.820657730102539e-05, 0.038726806640625, 0.0022907257080078125, 0.013641357421875, 0.01171875, -0.0212554931640625, -0.034088134765625, -0.00794219970703125, -0.0426025390625, -0.01361846923828125, -0.0013256072998046875, -0.022857666015625, -0.0196990966796875, 0.0296478271484375, -0.0697021484375, 0.03594970703125, 0.0238494873046875, -0.003326416015625, -0.0021190643310546875, -0.01290130615234375, 0.01395416259765625, -0.021636962890625, 0.03875732421875, 0.00576019287109375, 0.0012025833129882812, -0.063720703125, 0.050079345703125, 0.0248870849609375, 0.0036067962646484375, 0.007350921630859375, -0.00270843505859375, 0.003093719482421875, -0.034423828125, -0.016571044921875, -0.01507568359375, 0.032958984375, -0.0245208740234375, -0.0256500244140625, 0.00041294097900390625, -0.031341552734375, 0.020904541015625, -0.01428985595703125, -0.013153076171875, 0.00785064697265625, -0.01293182373046875, 0.0045623779296875, -0.005382537841796875, 0.006343841552734375, 0.054595947265625, -0.040740966796875, -0.01444244384765625, -0.0163116455078125, -0.0029850006103515625, -0.0185546875, 0.0616455078125, 0.03668212890625, -0.019927978515625, -0.0089569091796875, -0.0380859375, 0.00650787353515625, -0.0255584716796875, 0.0027599334716796875, -0.0290679931640625, -0.00978851318359375, -0.036956787109375, -0.0156402587890625, -0.01316070556640625, 0.0557861328125, -0.01525115966796875, -0.038360595703125, -0.0244598388671875, 0.053009033203125, -0.036712646484375, -0.04632568359375, 0.01306915283203125, 0.002361297607421875, -0.019439697265625, -0.0196533203125, -0.006572723388671875, -0.01392364501953125, 0.0208740234375, -0.002414703369140625, -0.03631591796875, 0.0084075927734375, 0.040740966796875, -0.0149078369140625, -0.0299835205078125, 0.0211181640625, 0.026123046875, -0.042755126953125, -0.035675048828125, -0.02197265625, 0.0238189697265625, -0.0014314651489257812, -0.0164794921875, 0.029754638671875, -0.0075836181640625, -0.0145111083984375, -0.024200439453125, -0.0062713623046875, 0.01422882080078125, -0.003047943115234375, -0.04327392578125, 0.00020837783813476562, 0.013702392578125, 0.01922607421875, 0.00753021240234375, -0.0195465087890625, 0.0286102294921875, 0.049530029296875, 0.01462554931640625, 0.004024505615234375, 0.0379638671875, -0.00698089599609375, -0.0266265869140625, -0.0207061767578125, -0.00817108154296875, 0.02215576171875, -0.00972747802734375, -0.01049041748046875, 0.0003726482391357422, -0.01548004150390625, 0.05413818359375, 0.0235137939453125, 0.017730712890625, 0.020477294921875, -0.00391387939453125, 0.007537841796875, 0.0308685302734375, -0.0178070068359375, -0.0246124267578125, -0.025726318359375, -0.03582763671875, -0.018585205078125, -0.03564453125, -0.017059326171875, -0.06591796875, 0.011749267578125, -0.002681732177734375, 0.0090789794921875, 0.0400390625, 0.020538330078125, -0.007110595703125, -0.0117645263671875, -0.03875732421875, -0.0499267578125, 0.021270751953125, -0.050933837890625, 0.05072021484375, 0.021820068359375, -0.000980377197265625, 0.015228271484375, -0.01288604736328125, 0.0117340087890625, 0.01177978515625, 0.0447998046875, 0.0125732421875, -0.036895751953125, -0.030181884765625, 0.0138092041015625, 0.005550384521484375, -0.0227813720703125, -0.007080078125, 0.01393890380859375, 0.00623321533203125, 0.02996826171875, -0.055419921875, 0.0155029296875, -0.02606201171875, -0.02056884765625, -0.00823974609375, 0.0255584716796875, -0.05157470703125, -0.026153564453125, 0.0323486328125, 0.003917694091796875, -0.040802001953125, -0.0183258056640625, 0.0279998779296875, -0.0228729248046875, 0.007312774658203125, 0.0059051513671875, -0.0032100677490234375, -0.0184783935546875, -0.047576904296875, 0.0093841552734375, 0.0428466796875, 0.0089569091796875, 0.0252532958984375, -0.0201263427734375, 0.004825592041015625, -0.007244110107421875, 0.00803375244140625, 0.027740478515625, -0.0065155029296875, 0.0003685951232910156, -0.040618896484375, 0.0007162094116210938, 0.0160980224609375, 0.006683349609375, -0.014556884765625, -0.0016107559204101562, -0.037567138671875, 0.0325927734375, 0.005401611328125, 0.00911712646484375, -0.037872314453125, 0.041259765625, 0.0201568603515625, 0.030181884765625, 0.0126495361328125, 0.00634002685546875, -0.0187835693359375, 0.036590576171875, 0.0251312255859375, 0.020263671875, -0.013671875, 0.0260467529296875, 0.0087890625, -0.04327392578125, -0.0270233154296875, -0.01342010498046875, 0.0126495361328125, -0.0128021240234375, 0.05682373046875, -0.00909423828125, -0.0225067138671875, -0.00693511962890625, -0.00849151611328125, -0.01995849609375, 0.0249786376953125, 0.0057373046875, -0.018157958984375, 0.00255584716796875, -0.01629638671875, 0.047027587890625, 4.124641418457031e-05, 0.045257568359375, -0.0012578964233398438, -0.003124237060546875, -0.03778076171875, -0.005828857421875, -0.028106689453125, 0.004497528076171875, 0.0274810791015625, -0.04071044921875, -0.025665283203125, 0.0093231201171875, 0.0224456787109375, 0.0162353515625, 0.01641845703125, -0.004291534423828125, -0.01111602783203125, -0.0274658203125, -0.01486968994140625, 0.004180908203125, 0.0171661376953125, -0.00897216796875, -0.0323486328125, 0.033233642578125, 0.007537841796875, -0.0123138427734375, -0.0303802490234375, 0.01548004150390625, -0.0207672119140625, -0.0196533203125, -0.006938934326171875, 0.005847930908203125, -0.00537109375, -0.015045166015625, 0.041839599609375, 0.045562744140625, 0.00011521577835083008, -0.032684326171875, -0.016693115234375, -0.0154571533203125, -0.0200347900390625, -0.034210205078125, 0.0034465789794921875, -0.0229034423828125, -0.054168701171875, 0.0092315673828125, 0.00855255126953125, -0.04180908203125, 0.006320953369140625, -0.016357421875, -0.004421234130859375, -0.01812744140625, 0.0089569091796875, -0.01654052734375, -0.019775390625, 0.0198211669921875, 0.012054443359375, 0.0237579345703125, 0.0017461776733398438, 0.0188751220703125, 0.0149688720703125, 0.002712249755859375, -0.0108795166015625, -0.047454833984375, -0.01971435546875, -0.01399993896484375, -0.040252685546875, -0.00652313232421875, -0.004047393798828125, 0.0223846435546875, 0.036773681640625, -0.0222930908203125, 0.0027027130126953125, -0.01329803466796875, 0.0164794921875, -0.037200927734375, 0.0118560791015625, -0.01520538330078125, 0.0135040283203125, -0.004425048828125, 0.0019063949584960938, 0.0032196044921875, -0.045013427734375, -0.0059356689453125, 0.001361846923828125, -0.0016574859619140625, 0.0298309326171875, -0.0167388916015625, 0.031646728515625, -0.006130218505859375, 0.019073486328125, 0.0106048583984375, 0.013275146484375, 0.0244598388671875, -0.013580322265625, 0.002704620361328125, 0.0066375732421875, 0.037353515625, -0.012603759765625, 0.0416259765625, 0.0035381317138671875, 0.002346038818359375, -0.03668212890625, -0.0223388671875, 0.00787353515625, -0.0230560302734375, 0.005207061767578125, -0.032623291015625, 0.004138946533203125, -0.0184783935546875, -0.006626129150390625, 0.0186767578125, -0.032989501953125, 0.0034637451171875, 0.00791168212890625, 0.019378662109375, -0.038909912109375, -0.00621795654296875, -0.016204833984375, -0.00782012939453125, -0.0180206298828125, 0.01499176025390625, 0.0421142578125, -0.006801605224609375, -0.04193115234375, 0.017791748046875, 0.00458526611328125, -0.00124359130859375, -0.0103759765625, 0.041748046875, 0.01708984375, -0.0120086669921875, -0.037994384765625, -0.0088653564453125, 0.0268707275390625, -0.0079803466796875, 0.0086822509765625, 0.005435943603515625, 0.04376220703125, -0.0194244384765625, 0.002155303955078125, -0.0219573974609375, -0.057525634765625, 0.01090240478515625, -0.0143280029296875, 0.0035858154296875, 0.0130462646484375, 0.00423431396484375, -0.00893402099609375, -0.048980712890625, -0.040130615234375, 0.03387451171875, 0.0187530517578125, -0.0203704833984375, 0.0097503662109375, 0.0200653076171875, -0.009857177734375, 0.004638671875, -0.0032806396484375, -0.0198822021484375, -0.010986328125, 0.0176849365234375, 0.052398681640625, -0.008087158203125, -0.03521728515625, -0.031158447265625, -0.0178375244140625, -0.002780914306640625, -0.012237548828125, 0.0048980712890625, -0.0213470458984375, 0.040374755859375, -0.0008883476257324219, 0.0147857666015625, -0.0250091552734375, -0.01415252685546875, 0.0240478515625, -0.01453399658203125, -0.014404296875, 0.04888916015625, 0.011871337890625, -0.022064208984375, 0.0106353759765625, -0.035980224609375, -0.015167236328125, -0.0181427001953125, -0.0162811279296875, -0.01343536376953125, 0.03564453125, 0.016693115234375, -0.0009708404541015625, 0.023193359375, -0.01465606689453125, -0.00771331787109375, 0.013397216796875, 0.01528167724609375, 0.0372314453125, 0.02691650390625, 0.0127410888671875, -0.003997802734375, -0.0105133056640625, 0.035552978515625, 0.03564453125, -0.038543701171875, 0.0024013519287109375, -0.0125274658203125, -0.02777099609375, 0.0254669189453125, 0.01070404052734375, 0.0006079673767089844, -0.022430419921875, -0.0166778564453125, -0.024871826171875, -0.0169219970703125, 0.017608642578125, 0.0214385986328125, -0.01428985595703125, -0.0004189014434814453, -0.0037212371826171875, 0.0008759498596191406, -0.022705078125, 0.01210784912109375, 0.0147705078125, -0.0215911865234375, 0.022552490234375, 0.01006317138671875, 0.0169219970703125, -0.0122528076171875, -0.01041412353515625, 0.00782012939453125, 0.00727081298828125, 0.0006103515625, 0.0155181884765625, -0.004730224609375, 0.004486083984375, 0.01491546630859375, 0.00888824462890625, -0.016387939453125, -0.037567138671875, 0.01474761962890625, -0.007266998291015625, 0.0489501953125, 0.01221466064453125, -0.001377105712890625, 0.032196044921875, 0.018585205078125, 0.022674560546875, -0.0104522705078125, -0.04437255859375, -0.007396697998046875, 0.012298583984375, -0.0013332366943359375, 0.00974273681640625, -0.046295166015625, 0.048309326171875, -0.0038013458251953125, 0.00146484375, 0.032440185546875, 0.00959014892578125, -0.0127410888671875, 0.0098419189453125, 0.0140228271484375, -0.00983428955078125, -0.0335693359375, 0.0291290283203125, -0.02606201171875, -0.0237884521484375, -0.0263519287109375, 0.0221710205078125, 0.01049041748046875, 0.0064697265625, 0.0396728515625, 0.01363372802734375, 0.01082611083984375, 0.00969696044921875, 0.0035114288330078125, -0.0013570785522460938, -0.032806396484375, -0.00033354759216308594, 0.026763916015625, 0.0010557174682617188, -0.025665283203125, -0.002040863037109375, 0.048553466796875, -0.0011968612670898438, 0.00896453857421875, 0.01038360595703125, -0.005275726318359375, -0.01235198974609375, -0.004852294921875, -0.017730712890625, -0.00630950927734375, -0.0158843994140625, -0.02996826171875, -0.025848388671875, 0.0197296142578125, 0.006317138671875, -0.0115203857421875, -0.0024871826171875, 0.02130126953125, 0.00783538818359375, -0.0020618438720703125, -0.0008769035339355469, -0.005535125732421875, 0.0260467529296875, 0.040679931640625, 0.009246826171875, 0.0108795166015625, 0.01287078857421875, 0.0215606689453125, -0.0179443359375, -0.0189666748046875, -0.0013647079467773438, 0.0122833251953125, 0.0186767578125, -0.0242462158203125, -0.005390167236328125, -0.01099395751953125, -0.005306243896484375, -0.03704833984375, 0.0

### amazon data

In [35]:
embed_cols = ['preprocessed_description', 'image', 'rating_number', 'price', 'average_rating', 'parent_asin']
data_to_embed = df_sample[embed_cols].to_dict(orient="records")

In [37]:
point_structs = [PointStruct(
    id = i,
    vector = get_embedding(row["preprocessed_description"]),
    payload = row
) for i, row in enumerate(data_to_embed)]

In [38]:
len(point_structs)

50

### write to qdrant

In [39]:
qdrant_client.upsert(
    collection_name="amazon-electronics-items-collection-01",
    points=point_structs
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

### function for data retrieval

In [42]:
def retrieve_from_qdrant(query, k=5):
    response = qdrant_client.query_points(
        collection_name="amazon-electronics-items-collection-01",
        query=get_embedding(query),
        limit=k
    )
    return response

In [44]:
retrieve_from_qdrant("do you have a usd connectable fan for hot weather?").points
# extra words such as hot weather make it harder for retrieval

[ScoredPoint(id=49, version=1, score=0.38531762, payload={'preprocessed_description': 'ThreeH USB Fan Laptop Cooling Pad with 3 Fans & Blue LED Lights for Laptop PS3 / PS4 / PS Slim H-UF01 Size: Fits 10-15" laptops - Works fine for laptops either smaller or larger than its size. USB port: Powered through USB port,anti-slide. Design: 3 Blue LED lights built into the pad. Good heat dissipation: 3 Fans to avoid overheating,keep your computer good performance. Anti-slide: Round rubber pad with a high friction coefficient on four corner of the fan around to ensure that the notebook will not be damaged by sliding.', 'image': 'https://m.media-amazon.com/images/I/41kKfMW9IYL._AC_.jpg', 'rating_number': 386, 'price': 16.99, 'average_rating': 3.8, 'parent_asin': 'B016KQ7IGG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.28863275, payload={'preprocessed_description': 'KMC 6-Outlet Surge Tap, 2 USB Ports (3.4A), 980 Joules Surge Protector, White (2 Pack) Multi Outlet: 6 AC outlets (15A/125V/1875W) can meet the need of 6 devices at the same time. With built-in surge protector (980J), it can ensure safety. When the “Protected” indicator LED light turns on, it shows your devices are protected against electrical spikes at the maximum. Dual Smart USB Charging Ports: 5V 3.4A shared rating; high-speed USB ports automatically detect charging devices and deliver optimal charging speed, up to 2.4A per port. Portable Travel Charger: Compact size plug-in adapter only occupies 1 wall socket which is a nice outlet saver; ideal for smart phones, tablets, laptop, kitchen appliances and other electronic accessories. Wide spacing between outlets and USB ports allow you to charge up to 2 devices simultaneously; ideal for power adapters and bulky plugs Space And Installation:Space-saving design can be placed strategically behind an entertainment center or desk, or mounted on the wall,screws included. Great gifts for your friends. Our Support Guarantee: Our friendly and reliable customer service will respond to you within 24 hours! You can purchase with confidence, with our 12-month replacement warranty, or 30-day money back guarantee!', 'image': 'https://m.media-amazon.com/images/I/31r9wTnUQkL._AC_.jpg', 'rating_number': 387, 'price': 11.19, 'average_rating': 4.7, 'parent_asin': 'B08F9T8LLQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.26920348, payload={'preprocessed_description': 'USB 3.0 Switch Selector, USB Switch 2 in 1 Out for 2 Computers Sharing 1 USB Device, Such as Mouse Printer Keyboard Scanner Flash Disk, 2pcs USB 3.0 Cables Included This USB Switch gives you the ability to operate two computers with a click of a button. With this USB 3.0 Switch you can share a USB device between two computers or even connecting a USB hub for sharing multiple devices between two computers. This USB Switch 3.0 diminutive and technology in one can help to keep your work space clean and organized, saving you precious time. This USB 3.0 Sharing switch allows you to access date on two separate computers through the same USB shared port. The powered red LED shows you exactly which device you are connected to for easy distinction. This USB 3.0 Switch Selector is USB-bus power supply, no charger required. It is a plug-and-play with no additional driver installation needed.', 'image': 'https://m.media-amazon.com/images/I/41140s+85lL.jpg', 'rating_number': 127, 'price': 18.98, 'average_rating': 3.3, 'parent_asin': 'B09BQ5V2J5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=1, score=0.26205194, payload={'preprocessed_description': 'MAVINEX USB C Hub 4 Ports USB 3.0 UltraSlim SuperSpeed 5Gbps Aluminum Compatible with PC, MacBook, Surface Pro, XPS, Flash Drive, Mobile HDD 【SuperSpeed Data Transfer】MAVINEX USB 3.0 extender transfer data up to 5Gbps, 10X faster than USB 2.0. An HD movie can be transferred within seconds. 【Easy Expansion】Split one USB 3.0 port into four USB 3.0 ports, easily connect USB-A devices to your laptop with this USB expander, such as USB flash drive, mouse, keyboard, speaker, game controller, HDD and many other gadgets that support OTG. 【Plug & Play】No extra driver needed, plug into the USB 3.0 Port on your laptop and enjoy amazingly fast data sync! 【Incredible Durability & Safety】The built-in smart chip avoids overcurrent, overvoltage, short circuit and overheat. Unlike ABS, Aluminum shell with a nice metallic finish provides better heat dissipation. Compact and lightweight, perfect size for business traveling. 【Wide Compatibility】MAVINEX USB C Hub with 4 Ports compatible with iMac, MacBook, MacBook Air, Mac Pro/ Mini, Surface Pro, XPS, Notebook, PC; Windows 10/8/8. 1/7/ Vista/ XP and Mac OS X, Linux, and Chrome OS.', 'image': 'https://m.media-amazon.com/images/I/31Wj9B3-WIL._AC_.jpg', 'rating_number': 1950, 'price': 5.99, 'average_rating': 4.6, 'parent_asin': 'B0B4623J2B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=1, score=0.25675082, payload={'preprocessed_description': 'Onite 2pcs of USB to DC 4.0x1.7mm Barrel Jack Power Cable Charger Cord for PSP 3000 2000 1000, Tablet, Cellphone, Laptop, Netbook, Electronics (6.6ft/2m) ', 'image': 'https://m.media-amazon.com/images/I/510Tlq0pH0L._AC_.jpg', 'rating_number': 152, 'price': None, 'average_rating': 4.5, 'parent_asin': 'B076Q82C9F'}, vector=None, shard_key=None, order_value=None)]